/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Carlos
 */
public class VentAcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form VentAcercaDe
     */
    public VentAcercaDe() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        lblIcono = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca De...");
        setAlwaysOnTop(true);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        txtInfo.setEditable(false);
        txtInfo.setColumns(20);
        txtInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtInfo.setRows(5);
        txtInfo.setText("Desarrollado por: \nCarlos Alberto Riveros Varela - Ingeniero de Sistemas T.P. 25255-309007 CND\ncariverosv@unal.edu.co\n\nPara el Departamento de Ingeniería Eléctrica y Electrónica de la Universidad Nacional \nde Colombia bajo la Resolución 1331 del 05 de Mayo del 2015 y la Resolución 3607\ndel 24 de Septiembre del 2015 .\n\nTodos los íconos empleados en este producto son de libre acceso:\n\nMust Have creado por Visual Pharm\nDisponible en: https://www.iconfinder.com/iconsets/musthave\nLicencia: Attribution-NoDerivs 3.0 Unported (CC BY-ND 3.0)\nhttp://creativecommons.org/licenses/by-nd/3.0/\n\nSimplicio creado por Neurovit\nDisponible en: https://www.iconfinder.com/iconsets/simplicio\nLicencia: Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)\nhttp://creativecommons.org/licenses/by-sa/3.0/\n\nPretty Office 10 creado por Custom Icon Design\nDisponible en: https://www.iconfinder.com/iconsets/pretty-office-10\nLicencia: Free for non comercial use\n\nHuman o2 creado por Oliver Scholtz (y otros)\nDisponible en: https://www.iconfinder.com/iconsets/humano2\nLicencia: Free for non comercial use\n\nVista General creado por Lokas Software\nDisponible en: https://www.iconfinder.com/iconsets/vista-general\nLicencia: Creative Commons (Attribution 3.0 Unported)\nhttp://creativecommons.org/licenses/by/3.0/\n\nCrystal Project creado por Everaldo Coelho\nDisponible en: https://www.iconfinder.com/iconsets/crystalproject\nLicencia: LGPL\nhttp://www.gnu.org/licenses/lgpl.html");
        jScrollPane1.setViewportView(txtInfo);

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png"))); // NOI18N

        lblTitulo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo1.setText("Software para la Gestión Académica del Departamento de");

        lblTitulo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo2.setText("Ingeniería Eléctrica y  Electrónica");

        lblTitulo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo3.setText("Universidad Nacional de Colombia -  V. 1.1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo3)
                    .addComponent(lblTitulo1)
                    .addComponent(lblTitulo2))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitulo3))
                    .addComponent(lblIcono))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
