/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdEnviarHorarioCorreo;
import business.CmdEnviarTodosHorariosCorreo;
import business.ButtonHandler;
import generalities.Utilidades;
import javax.swing.BorderFactory;
import javax.swing.JTable;

/**
 *
 * @author Carlos
 */
public class VentFormatoCorreoHorario extends javax.swing.JFrame {

    private JTable jTablehorarioDocente;
    private VentHorarioDocente ventanaHorarioDoc;
    private VentProgAca ventProgAca;

    /**
     * Creates new form VentFormatoCorreoHorario
     */
    public VentFormatoCorreoHorario(JTable horarioDocente, VentHorarioDocente ventanaHorarioDoc, VentProgAca ventProgAca) {
        this.jTablehorarioDocente = horarioDocente;
        this.ventanaHorarioDoc = ventanaHorarioDoc;
        this.ventProgAca = ventProgAca;
        initComponents();
        desplegarFormato();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAsunto = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCuerpoMensaje = new javax.swing.JTextArea();
        if(ventProgAca == null){
            btnAceptar = new javax.swing.JButton();
            btnAceptar.addActionListener(new ButtonHandler(new CmdEnviarHorarioCorreo(jTablehorarioDocente, ventanaHorarioDoc, this, btnAceptar)));
        } else {
            btnAceptar = new javax.swing.JButton();
            btnAceptar.addActionListener(new ButtonHandler(new CmdEnviarTodosHorariosCorreo(ventProgAca, this, btnAceptar)));
        }
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formato de correo electrónico");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());

        lblAsunto.setText("Asunto:");

        txtCuerpoMensaje.setColumns(10);
        txtCuerpoMensaje.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCuerpoMensaje.setLineWrap(true);
        txtCuerpoMensaje.setRows(5);
        txtCuerpoMensaje.setBorder(BorderFactory.createTitledBorder("Cuerpo del mensaje"));
        jScrollPane1.setViewportView(txtCuerpoMensaje);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnAceptar.setText("Enviar");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAsunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsunto)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextArea txtCuerpoMensaje;
    // End of variables declaration//GEN-END:variables

    private void desplegarFormato() {
        String[] formatoCorreo = (String[]) Utilidades.leerArchivo("FormatoCorreo");
        if (formatoCorreo != null) {
            txtAsunto.setText(formatoCorreo[0]);
            txtCuerpoMensaje.setText(formatoCorreo[1]);
        }
    }

    public String getAsunto() {
        return txtAsunto.getText();
    }

    public String getCuerpo() {
        return txtCuerpoMensaje.getText();
    }

    public void guardarFormatoCorreo() {
        String[] formatoCorreo = (String[]) Utilidades.leerArchivo("FormatoCorreo");
        if (formatoCorreo == null) {
            formatoCorreo = new String[2];
        }
        formatoCorreo[0] = getAsunto();
        formatoCorreo[1] = getCuerpo();
        Utilidades.escribirArchivo("FormatoCorreo", formatoCorreo);
    }

}
