/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdElegirColoresHorarios;
import business.ButtonHandler;
import business.Horario;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author Carlos
 */
public class VentColoresHorarios extends javax.swing.JFrame{

    /**
     * Creates new form VentColoresHorarios
     */
    public VentColoresHorarios() {
        Horario.inicializarColores();
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1Grupo = new javax.swing.JLabel();
        lblColorGr1 = new javax.swing.JLabel();
        CmdElegirColoresHorarios cmdElegirColoresHorarios = new CmdElegirColoresHorarios(this);
        lblColorGr1.addMouseListener(new ButtonHandler(cmdElegirColoresHorarios));
        lblColorGr1.setOpaque(true);
        lblColorGr1.setBackground(Horario.UN_GRUPO);
        lblColorGr1.setBorder(BorderFactory.createLineBorder(Color.black));
        lbl2Grupos = new javax.swing.JLabel();
        lbl3Grupos = new javax.swing.JLabel();
        lbl4Grupos = new javax.swing.JLabel();
        lbl5MasGrupos = new javax.swing.JLabel();
        lblColorGr2 = new javax.swing.JLabel();
        lblColorGr2.addMouseListener(new ButtonHandler(cmdElegirColoresHorarios));
        lblColorGr2.setOpaque(true);
        lblColorGr2.setBackground(Horario.DOS_GRUPOS);
        lblColorGr2.setBorder(BorderFactory.createLineBorder(Color.black));
        lblColorGr3 = new javax.swing.JLabel();
        lblColorGr3.addMouseListener(new ButtonHandler(cmdElegirColoresHorarios));
        lblColorGr3.setOpaque(true);
        lblColorGr3.setBackground(Horario.TRES_GRUPOS);
        lblColorGr3.setBorder(BorderFactory.createLineBorder(Color.black));
        lblColorGr4 = new javax.swing.JLabel();
        lblColorGr4.addMouseListener(new ButtonHandler(cmdElegirColoresHorarios));
        lblColorGr4.setOpaque(true);
        lblColorGr4.setBackground(Horario.CUATRO_GRUPOS);
        lblColorGr4.setBorder(BorderFactory.createLineBorder(Color.black));
        lblColorGr5 = new javax.swing.JLabel();
        lblColorGr5.addMouseListener(new ButtonHandler(cmdElegirColoresHorarios));
        lblColorGr5.setOpaque(true);
        lblColorGr5.setBackground(Horario.CINCO_GRUPOS);
        lblColorGr5.setBorder(BorderFactory.createLineBorder(Color.black));
        btnElegirColoresHorarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Elección de colores para casillas de horarios");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());

        lbl1Grupo.setText("1 Grupo");

        lbl2Grupos.setText("2 Grupos");

        lbl3Grupos.setText("3 Grupos");

        lbl4Grupos.setText("4 Grupos");

        lbl5MasGrupos.setText("5 Grupos");

        btnElegirColoresHorarios.addActionListener(new ButtonHandler(cmdElegirColoresHorarios));
        btnElegirColoresHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnElegirColoresHorarios.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnElegirColoresHorarios)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl5MasGrupos)
                            .addGap(18, 18, 18)
                            .addComponent(lblColorGr5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl4Grupos)
                            .addGap(18, 18, 18)
                            .addComponent(lblColorGr4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl3Grupos)
                            .addGap(18, 18, 18)
                            .addComponent(lblColorGr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl2Grupos)
                                .addComponent(lbl1Grupo))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblColorGr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblColorGr2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1Grupo)
                    .addComponent(lblColorGr1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorGr2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2Grupos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorGr3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3Grupos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorGr4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4Grupos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5MasGrupos)
                    .addComponent(lblColorGr5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnElegirColoresHorarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegirColoresHorarios;
    private javax.swing.JLabel lbl1Grupo;
    private javax.swing.JLabel lbl2Grupos;
    private javax.swing.JLabel lbl3Grupos;
    private javax.swing.JLabel lbl4Grupos;
    private javax.swing.JLabel lbl5MasGrupos;
    private javax.swing.JLabel lblColorGr1;
    private javax.swing.JLabel lblColorGr2;
    private javax.swing.JLabel lblColorGr3;
    private javax.swing.JLabel lblColorGr4;
    private javax.swing.JLabel lblColorGr5;
    // End of variables declaration//GEN-END:variables


    public JLabel getLblColorGr1() {
        return lblColorGr1;
    }

    public JLabel getLblColorGr2() {
        return lblColorGr2;
    }

    public JLabel getLblColorGr3() {
        return lblColorGr3;
    }

    public JLabel getLblColorGr4() {
        return lblColorGr4;
    }

    public JLabel getLblColorGr5() {
        return lblColorGr5;
    }

}
