/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdCrearNivelEstudio;
import business.ButtonHandler;
import business.ComboBoxNivelEstudio;
import business.Observer;
import dataDB.Nivelestudio;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VentCrearNivelEstudio extends javax.swing.JFrame {

    private Nivelestudio nivelEstudio;
    private ComboBoxNivelEstudio cbNivelEstudio;

    /**
     * Creates new form VentCrearNivelEstudio
     */
    public VentCrearNivelEstudio() {
        initComponents();
        this.setVisible(true);
    }

    public VentCrearNivelEstudio(ComboBoxNivelEstudio cbNivelEstudio) {
        this.cbNivelEstudio = cbNivelEstudio; 
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNuevoNivelEstudio = new javax.swing.JLabel();
        txtNivelEstudio = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nivel de estudio");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblNuevoNivelEstudio.setText("Nombre nivel de estudio:");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        CmdCrearNivelEstudio btnCrearNivelEstudio = new CmdCrearNivelEstudio(this, btnAceptar);
        btnCrearNivelEstudio.register((Observer) cbNivelEstudio);
        btnAceptar.addActionListener(new ButtonHandler(btnCrearNivelEstudio));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnAceptar.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblNuevoNivelEstudio)
                .addGap(18, 18, 18)
                .addComponent(txtNivelEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoNivelEstudio)
                    .addComponent(txtNivelEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cerrar();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblNuevoNivelEstudio;
    private javax.swing.JTextField txtNivelEstudio;
    // End of variables declaration//GEN-END:variables

    public String getNombreNivelEstudio() {
        return txtNivelEstudio.getText().toUpperCase();
    }

    private void setNombreNivelEstudio(String nombreNivelEstudio) {
        this.txtNivelEstudio.setText(nombreNivelEstudio);
    }

    public void setNivelEstudio(Nivelestudio nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
        setNombreNivelEstudio(nivelEstudio.getNivelEstudio());
        setTitle("Modificar nivel de estudio");
        setBtnActionCommand("Modificar");
    }

    public Nivelestudio getNivelEstudio() {
        return this.nivelEstudio;
    }

    public void setBtnActionCommand(String accion) {
        this.btnAceptar.setActionCommand(accion);
        this.btnAceptar.setText(accion);
    }

    public void cerrar() {
        this.dispose();
    }

    public void confirmarNivelEstudioAgregado() {
        JOptionPane.showMessageDialog(this, "Nivel de estudio agregado correctamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    }

    public void confirmarNivelEstudioModificado() {
        JOptionPane.showMessageDialog(this, "Nivel de estudio modificado correctamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    }

}
