/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.ButtonHandler;
import business.CmdImportarArchAsig;
import business.CmdImportarArchDocentes;
import business.CmdImportarArchSalones;
import business.CmdImportarPlanesEstudio;
import business.CmdSalir;
import data.Manejador;
import data.Usuario;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VentPrincipal extends JFrame {

    private boolean creable = true;
    private boolean modificable = true;
    private boolean eliminable = true;
    private Usuario usuario;

    /**
     * Creates new form VentPrincipal
     */
    public VentPrincipal(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        mniCambiarCorreo.setVisible(false);
        mniModPrerrequisitos.setVisible(false);
        String permisos = "";
        try {
            if (!Usuario.consultarPermiso(usuario.getNomUsuario(), Usuario.PRIV_INSERTAR)) {
                permisos = " - No tiene permisos para crear";
                creable = false;
                jMenuUsuarios.setVisible(false);
                btnAdAsig.setEnabled(false);
                btnAdDoc.setEnabled(false);
                btnAdEdificio.setEnabled(false);
                btnAdSalon.setEnabled(false);
                btnProgAca.setEnabled(false);
                btnAdProgDesdeAnterior.setEnabled(false);
                jMenuArchivo.setEnabled(false);
                jMenuPlanesEstudio.setEnabled(false);
                mniAdAsignatura.setEnabled(false);
                mniAdTipologia.setEnabled(false);
                mniAdNivelEstudio.setEnabled(false);
                mniAdDocente.setEnabled(false);
                mniAdTipoContrato.setEnabled(false);
                mniAdSalon.setEnabled(false);
                mniAdEdificio.setEnabled(false);
                mniCrearProgAca.setEnabled(false);
                mniCrearNuevaDesdeAnterior.setEnabled(false);
                mniImportarProgAca.setEnabled(false);
                mniModAsigPlanEstudio.setVisible(false);
                mniVincularAsigPlanEstudio.setVisible(false);

            }
            if (!Usuario.consultarPermiso(usuario.getNomUsuario(), Usuario.PRIV_ACTUALIZAR)) {
                permisos = permisos + " - No tiene permisos para modificar";
                modificable = false;
            }
            if (!Usuario.consultarPermiso(usuario.getNomUsuario(), Usuario.PRIV_ELIMINAR)) {
                permisos = permisos + " - No tiene permisos para eliminar";
                eliminable = false;
            }
        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.addWindowListener(new ButtonHandler(new CmdSalir()));
        setTitle("Aplicativo Gestión Académica DPTOIEE - " + usuario.getNomUsuario() + permisos);
        setSize(getMaximumSize());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        btnAdDoc = new javax.swing.JButton();
        btnAdAsig = new javax.swing.JButton();
        btnAdEdificio = new javax.swing.JButton();
        btnAdSalon = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnProgAcaAnterior = new javax.swing.JButton();
        btnProgAca = new javax.swing.JButton();
        btnAdProgDesdeAnterior = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuImportar = new javax.swing.JMenu();
        mniImpDocentes = new javax.swing.JMenuItem();
        mniImpDocentes.addActionListener(new ButtonHandler(new business.CmdImportarArchDocentes(mniImpDocentes)));
        mniImpAsignaturas = new javax.swing.JMenuItem();
        mniImpPlanEstudios = new javax.swing.JMenuItem();
        mniImpPlanEstudios.addActionListener(new ButtonHandler(new business.CmdImportarPlanesEstudio(mniImpPlanEstudios)));
        mniImpSalones = new javax.swing.JMenuItem();
        mniImpSalones.addActionListener(new ButtonHandler(new business.CmdImportarArchSalones(mniImpSalones)));
        mniSalir = new javax.swing.JMenuItem();
        mniSalir.addActionListener(new ButtonHandler(new CmdSalir()));
        jMenuAsignaturas = new javax.swing.JMenu();
        mniAdAsignatura = new javax.swing.JMenuItem();
        mniModAsignatura = new javax.swing.JMenuItem();
        mniVincularAsigPlanEstudio = new javax.swing.JMenuItem();
        jMenuTipologias = new javax.swing.JMenu();
        mniAdTipologia = new javax.swing.JMenuItem();
        mniModTipologia = new javax.swing.JMenuItem();
        jMenuNivelesEstudio = new javax.swing.JMenu();
        mniAdNivelEstudio = new javax.swing.JMenuItem();
        mniModNivelEstudio = new javax.swing.JMenuItem();
        jMenuPlanesEstudio = new javax.swing.JMenu();
        mniAdPlanEstudio = new javax.swing.JMenuItem();
        jMenuModPlanEstudio = new javax.swing.JMenu();
        mniModPlanEstudio = new javax.swing.JMenuItem();
        mniModPrerrequisitos = new javax.swing.JMenuItem();
        mniModAsigPlanEstudio = new javax.swing.JMenuItem();
        jMenuDocentes = new javax.swing.JMenu();
        mniAdDocente = new javax.swing.JMenuItem();
        mniModDocente = new javax.swing.JMenuItem();
        jMenuTiposContrato = new javax.swing.JMenu();
        mniAdTipoContrato = new javax.swing.JMenuItem();
        mniModTipoContrato = new javax.swing.JMenuItem();
        jMenuEspaciosFisicos = new javax.swing.JMenu();
        jMenuSalon = new javax.swing.JMenu();
        mniAdSalon = new javax.swing.JMenuItem();
        mniModSalon = new javax.swing.JMenuItem();
        jMenuEdificio = new javax.swing.JMenu();
        mniAdEdificio = new javax.swing.JMenuItem();
        mniModEdificio = new javax.swing.JMenuItem();
        jMenuProgAcad = new javax.swing.JMenu();
        mniVerProgAcaAnterior = new javax.swing.JMenuItem();
        mniCrearProgAca = new javax.swing.JMenuItem();
        mniCrearNuevaDesdeAnterior = new javax.swing.JMenuItem();
        mniImportarProgAca = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        mnINuevoUsua = new javax.swing.JMenuItem();
        mniCambiarPermisos = new javax.swing.JMenuItem();
        mniEliminarUsuarios = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        mniCambiarPass = new javax.swing.JMenuItem();
        mniCambiarCorreo = new javax.swing.JMenuItem();
        mniElegirColoresHorario = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        mniContenidos = new javax.swing.JMenuItem();
        mniAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setMinimumSize(new java.awt.Dimension(900, 500));

        jToolBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar.setFloatable(false);
        jToolBar.setRollover(true);

        btnAdDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/docente.png"))); // NOI18N
        btnAdDoc.setToolTipText("Agregar docente(Ctrl+D)");
        btnAdDoc.setFocusable(false);
        btnAdDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdDocActionPerformed(evt);
            }
        });
        jToolBar.add(btnAdDoc);

        btnAdAsig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/asignatura.png"))); // NOI18N
        btnAdAsig.setToolTipText("Agregar asignatura(CTRL + A)");
        btnAdAsig.setFocusable(false);
        btnAdAsig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdAsig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdAsigActionPerformed(evt);
            }
        });
        jToolBar.add(btnAdAsig);

        btnAdEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/edificio.png"))); // NOI18N
        btnAdEdificio.setToolTipText("Agregar edificio(CTRL + F)");
        btnAdEdificio.setFocusable(false);
        btnAdEdificio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdEdificio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdEdificioActionPerformed(evt);
            }
        });
        jToolBar.add(btnAdEdificio);

        btnAdSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/salon.png"))); // NOI18N
        btnAdSalon.setToolTipText("Agregar salón (CTRL + O)");
        btnAdSalon.setFocusable(false);
        btnAdSalon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdSalon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdSalonActionPerformed(evt);
            }
        });
        jToolBar.add(btnAdSalon);
        jToolBar.add(jSeparator2);

        btnProgAcaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/progAcaAnterior.png"))); // NOI18N
        btnProgAcaAnterior.setToolTipText("Abrir programación académica anterior(CTRL + R)");
        btnProgAcaAnterior.setFocusable(false);
        btnProgAcaAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProgAcaAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProgAcaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgAcaAnteriorActionPerformed(evt);
            }
        });
        jToolBar.add(btnProgAcaAnterior);

        btnProgAca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/progAca.png"))); // NOI18N
        btnProgAca.setToolTipText("Crear nueva programación académica(CTRL + P)");
        btnProgAca.setFocusable(false);
        btnProgAca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProgAca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProgAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgAcaActionPerformed(evt);
            }
        });
        jToolBar.add(btnProgAca);

        btnAdProgDesdeAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/crearDesdeAnterior.png"))); // NOI18N
        btnAdProgDesdeAnterior.setToolTipText("Crear programación académica desde una anterior");
        btnAdProgDesdeAnterior.setFocusable(false);
        btnAdProgDesdeAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdProgDesdeAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdProgDesdeAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdProgDesdeAnteriorActionPerformed(evt);
            }
        });
        jToolBar.add(btnAdProgDesdeAnterior);
        jToolBar.add(jSeparator1);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));

        jMenuArchivo.setMnemonic(KeyEvent.VK_A);
        jMenuArchivo.setText("Archivo");

        jMenuImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/importar.png"))); // NOI18N
        jMenuImportar.setText("Importar archivo...");

        mniImpDocentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/docentePeque.png"))); // NOI18N
        mniImpDocentes.setText("de Docentes");
        jMenuImportar.add(mniImpDocentes);

        mniImpAsignaturas.addActionListener(new ButtonHandler(new business.CmdImportarArchAsig(mniImpAsignaturas)));
        mniImpAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/asignaturaPeque.png"))); // NOI18N
        mniImpAsignaturas.setText("de asignaturas");
        jMenuImportar.add(mniImpAsignaturas);

        mniImpPlanEstudios.setText("de plan de estudios");
        jMenuImportar.add(mniImpPlanEstudios);

        mniImpSalones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/salonPeque.png"))); // NOI18N
        mniImpSalones.setText("de salones");
        jMenuImportar.add(mniImpSalones);

        jMenuArchivo.add(jMenuImportar);

        mniSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mniSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/salirPeque.png"))); // NOI18N
        mniSalir.setText("Salir");
        jMenuArchivo.add(mniSalir);

        jMenuBar.add(jMenuArchivo);

        jMenuAsignaturas.setMnemonic(KeyEvent.VK_S);
        jMenuAsignaturas.setText("Asignaturas");

        mniAdAsignatura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mniAdAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniAdAsignatura.setText("Agregar asignatura");
        mniAdAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdAsignaturaActionPerformed(evt);
            }
        });
        jMenuAsignaturas.add(mniAdAsignatura);

        mniModAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modificarPeque.png"))); // NOI18N
        mniModAsignatura.setText("Ver y modificar asignaturas");
        mniModAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModAsignaturaActionPerformed(evt);
            }
        });
        jMenuAsignaturas.add(mniModAsignatura);

        mniVincularAsigPlanEstudio.setText("Vincular asignaturas a planes de estudio");
        mniVincularAsigPlanEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVincularAsigPlanEstudioActionPerformed(evt);
            }
        });
        jMenuAsignaturas.add(mniVincularAsigPlanEstudio);

        jMenuTipologias.setText("Tipologías");

        mniAdTipologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniAdTipologia.setText("Agregar tipología");
        mniAdTipologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdTipologiaActionPerformed(evt);
            }
        });
        jMenuTipologias.add(mniAdTipologia);

        mniModTipologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modificarPeque.png"))); // NOI18N
        mniModTipologia.setText("Ver y modificar");
        mniModTipologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModTipologiaActionPerformed(evt);
            }
        });
        jMenuTipologias.add(mniModTipologia);

        jMenuAsignaturas.add(jMenuTipologias);

        jMenuNivelesEstudio.setText("Niveles de estudio");

        mniAdNivelEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniAdNivelEstudio.setText("Agregar nivel de estudio");
        mniAdNivelEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdNivelEstudioActionPerformed(evt);
            }
        });
        jMenuNivelesEstudio.add(mniAdNivelEstudio);

        mniModNivelEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modificarPeque.png"))); // NOI18N
        mniModNivelEstudio.setText("Ver y modificar");
        mniModNivelEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModNivelEstudioActionPerformed(evt);
            }
        });
        jMenuNivelesEstudio.add(mniModNivelEstudio);

        jMenuAsignaturas.add(jMenuNivelesEstudio);

        jMenuBar.add(jMenuAsignaturas);

        jMenuPlanesEstudio.setMnemonic(KeyEvent.VK_L);
        jMenuPlanesEstudio.setText("Planes de estudio");

        mniAdPlanEstudio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mniAdPlanEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniAdPlanEstudio.setText("Agregar plan de estudio");
        mniAdPlanEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdPlanEstudioActionPerformed(evt);
            }
        });
        jMenuPlanesEstudio.add(mniAdPlanEstudio);

        jMenuModPlanEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modificarPeque.png"))); // NOI18N
        jMenuModPlanEstudio.setText("Modificar u ocultar plan de estudio");

        mniModPlanEstudio.setText("Modificar descripción u ocultar plan");
        mniModPlanEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModPlanEstudioActionPerformed(evt);
            }
        });
        jMenuModPlanEstudio.add(mniModPlanEstudio);

        mniModPrerrequisitos.setText("Modificar prerrequisitos");
        jMenuModPlanEstudio.add(mniModPrerrequisitos);

        mniModAsigPlanEstudio.setText("Modificar asignaturas de un plan de estudios");
        mniModAsigPlanEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModAsigPlanEstudioActionPerformed(evt);
            }
        });
        jMenuModPlanEstudio.add(mniModAsigPlanEstudio);

        jMenuPlanesEstudio.add(jMenuModPlanEstudio);

        jMenuBar.add(jMenuPlanesEstudio);

        jMenuDocentes.setMnemonic(KeyEvent.VK_D);
        jMenuDocentes.setText("Docentes");

        mniAdDocente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mniAdDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniAdDocente.setText("Agregar docente");
        mniAdDocente.setToolTipText("Adicionar docente (Ctrl+D)");
        mniAdDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdDocenteActionPerformed(evt);
            }
        });
        jMenuDocentes.add(mniAdDocente);

        mniModDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modificarPeque.png"))); // NOI18N
        mniModDocente.setText("Ver y modificar docentes");
        mniModDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModDocenteActionPerformed(evt);
            }
        });
        jMenuDocentes.add(mniModDocente);

        jMenuTiposContrato.setText("Tipos de contrato");

        mniAdTipoContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniAdTipoContrato.setText("Agregar tipo de contrato");
        mniAdTipoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdTipoContratoActionPerformed(evt);
            }
        });
        jMenuTiposContrato.add(mniAdTipoContrato);

        mniModTipoContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modificarPeque.png"))); // NOI18N
        mniModTipoContrato.setText("Ver y modificar");
        mniModTipoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModTipoContratoActionPerformed(evt);
            }
        });
        jMenuTiposContrato.add(mniModTipoContrato);

        jMenuDocentes.add(jMenuTiposContrato);

        jMenuBar.add(jMenuDocentes);

        jMenuEspaciosFisicos.setMnemonic(KeyEvent.VK_E);
        jMenuEspaciosFisicos.setText("Espacios físicos");

        jMenuSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/salonPeque.png"))); // NOI18N
        jMenuSalon.setText("Salones");

        mniAdSalon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniAdSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniAdSalon.setText("Agregar salón");
        mniAdSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdSalonActionPerformed(evt);
            }
        });
        jMenuSalon.add(mniAdSalon);

        mniModSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modificarPeque.png"))); // NOI18N
        mniModSalon.setText("Ver y modificar salones");
        mniModSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModSalonActionPerformed(evt);
            }
        });
        jMenuSalon.add(mniModSalon);

        jMenuEspaciosFisicos.add(jMenuSalon);

        jMenuEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/edificioPeque.png"))); // NOI18N
        jMenuEdificio.setText("Edificios");

        mniAdEdificio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mniAdEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniAdEdificio.setText("Agregar edificio");
        mniAdEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdEdificioActionPerformed(evt);
            }
        });
        jMenuEdificio.add(mniAdEdificio);

        mniModEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modificarPeque.png"))); // NOI18N
        mniModEdificio.setText("Ver y modificar edificios");
        mniModEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModEdificioActionPerformed(evt);
            }
        });
        jMenuEdificio.add(mniModEdificio);

        jMenuEspaciosFisicos.add(jMenuEdificio);

        jMenuBar.add(jMenuEspaciosFisicos);

        jMenuProgAcad.setMnemonic(KeyEvent.VK_P);
        jMenuProgAcad.setText("Programación académica");

        mniVerProgAcaAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mniVerProgAcaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/verPeque2.png"))); // NOI18N
        mniVerProgAcaAnterior.setText("Abrir");
        mniVerProgAcaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVerProgAcaAnteriorActionPerformed(evt);
            }
        });
        jMenuProgAcad.add(mniVerProgAcaAnterior);

        mniCrearProgAca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mniCrearProgAca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        mniCrearProgAca.setText("Crear nueva");
        mniCrearProgAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCrearProgAcaActionPerformed(evt);
            }
        });
        jMenuProgAcad.add(mniCrearProgAca);

        mniCrearNuevaDesdeAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/crearNuevaDesdeAnteriorPeq.png"))); // NOI18N
        mniCrearNuevaDesdeAnterior.setText("Crear nueva a partir de una anterior");
        mniCrearNuevaDesdeAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCrearNuevaDesdeAnteriorActionPerformed(evt);
            }
        });
        jMenuProgAcad.add(mniCrearNuevaDesdeAnterior);

        mniImportarProgAca.addActionListener(new ButtonHandler(new business.CmdImportarProgAca(mniImportarProgAca)));
        mniImportarProgAca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/PrograImportarPeque.png"))); // NOI18N
        mniImportarProgAca.setText("Importar");
        jMenuProgAcad.add(mniImportarProgAca);

        jMenuBar.add(jMenuProgAcad);

        jMenuUsuarios.setMnemonic(KeyEvent.VK_U);
        jMenuUsuarios.setText("Usuarios");
        try{
            EntityManager entityM = Manejador.getManejador().gentEntityManager();
            entityM.createNativeQuery("SELECT 'u' FROM mysql.user u WHERE u.User ='"+usuario.getNomUsuario()+"' AND u.Create_user_priv ='Y'").getResultList();
            jMenuUsuarios.setVisible(true);
        }
        catch(PersistenceException ex){
            jMenuUsuarios.setVisible(false);
        }

        mnINuevoUsua.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnINuevoUsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/usuario.png"))); // NOI18N
        mnINuevoUsua.setText("Crear nuevo");
        mnINuevoUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnINuevoUsuaActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(mnINuevoUsua);

        mniCambiarPermisos.setText("Modificar permisos");
        mniCambiarPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCambiarPermisosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(mniCambiarPermisos);

        mniEliminarUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mniEliminarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        mniEliminarUsuarios.setText("Eliminar");
        mniEliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(mniEliminarUsuarios);

        jMenuBar.add(jMenuUsuarios);

        jMenuOpciones.setMnemonic(KeyEvent.VK_O);
        jMenuOpciones.setText("Opciones");

        mniCambiarPass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mniCambiarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/llavePeque.png"))); // NOI18N
        mniCambiarPass.setText("Cambiar contraseña");
        mniCambiarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCambiarPassActionPerformed(evt);
            }
        });
        jMenuOpciones.add(mniCambiarPass);

        mniCambiarCorreo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mniCambiarCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/correo.png"))); // NOI18N
        mniCambiarCorreo.setText("Cambiar correo electrónico");
        mniCambiarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCambiarCorreoActionPerformed(evt);
            }
        });
        jMenuOpciones.add(mniCambiarCorreo);

        mniElegirColoresHorario.setText("Elegir colores de horario");
        mniElegirColoresHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniElegirColoresHorarioActionPerformed(evt);
            }
        });
        jMenuOpciones.add(mniElegirColoresHorario);

        jMenuBar.add(jMenuOpciones);

        jMenuAyuda.setMnemonic(KeyEvent.VK_Y);
        jMenuAyuda.setText("Ayuda");

        mniContenidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniContenidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/ayuda.png"))); // NOI18N
        mniContenidos.setText("Contenido de ayuda");
        mniContenidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniContenidosActionPerformed(evt);
            }
        });
        jMenuAyuda.add(mniContenidos);

        mniAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/acercaDe.png"))); // NOI18N
        mniAcercaDe.setText("Acerca de...");
        mniAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(mniAcercaDe);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnINuevoUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnINuevoUsuaActionPerformed
        new VentanaCrearUsuario();
    }//GEN-LAST:event_mnINuevoUsuaActionPerformed

    private void mniAdDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdDocenteActionPerformed
        btnAdDocActionPerformed(evt);
    }//GEN-LAST:event_mniAdDocenteActionPerformed

    private void mniAdAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdAsignaturaActionPerformed
        btnAdAsigActionPerformed(evt);
    }//GEN-LAST:event_mniAdAsignaturaActionPerformed

    private void btnAdDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdDocActionPerformed
        new VentCrearDocente();
    }//GEN-LAST:event_btnAdDocActionPerformed

    private void btnAdAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdAsigActionPerformed
        new VentCrearAsignatura();
    }//GEN-LAST:event_btnAdAsigActionPerformed

    private void mniCambiarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCambiarPassActionPerformed
        new VentCambiarPass(usuario);
    }//GEN-LAST:event_mniCambiarPassActionPerformed

    private void mniCambiarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCambiarCorreoActionPerformed
        new VentCambiarCorreo(usuario);
    }//GEN-LAST:event_mniCambiarCorreoActionPerformed

    private void mniEliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarUsuariosActionPerformed
        new VentEliminarUsuarios();
    }//GEN-LAST:event_mniEliminarUsuariosActionPerformed

    private void btnAdEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdEdificioActionPerformed
        new VentCrearEdificio();
    }//GEN-LAST:event_btnAdEdificioActionPerformed

    private void mniAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAcercaDeActionPerformed
        new VentAcercaDe();
    }//GEN-LAST:event_mniAcercaDeActionPerformed

    private void mniAdTipologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdTipologiaActionPerformed
        new VentCrearTipologia();
    }//GEN-LAST:event_mniAdTipologiaActionPerformed

    private void mniAdNivelEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdNivelEstudioActionPerformed
        new VentCrearNivelEstudio();
    }//GEN-LAST:event_mniAdNivelEstudioActionPerformed

    private void mniAdPlanEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdPlanEstudioActionPerformed
        new VentCrearPlanEstudio();
    }//GEN-LAST:event_mniAdPlanEstudioActionPerformed

    private void mniAdTipoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdTipoContratoActionPerformed
        new VentCrearTipoContrato();
    }//GEN-LAST:event_mniAdTipoContratoActionPerformed

    private void mniAdEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdEdificioActionPerformed
        btnAdEdificioActionPerformed(evt);
    }//GEN-LAST:event_mniAdEdificioActionPerformed

    private void mniAdSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdSalonActionPerformed
        btnAdSalonActionPerformed(evt);
    }//GEN-LAST:event_mniAdSalonActionPerformed

    private void mniModDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModDocenteActionPerformed
        new VentDocentes(modificable, eliminable);
    }//GEN-LAST:event_mniModDocenteActionPerformed

    private void mniModAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModAsignaturaActionPerformed
        new VentAsignaturas(modificable, eliminable);
    }//GEN-LAST:event_mniModAsignaturaActionPerformed

    private void btnAdSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdSalonActionPerformed
        new VentCrearSalon();
    }//GEN-LAST:event_btnAdSalonActionPerformed

    private void btnProgAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgAcaActionPerformed
        new VentCrearProgAca(this);
    }//GEN-LAST:event_btnProgAcaActionPerformed

    private void btnProgAcaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgAcaAnteriorActionPerformed
        new VentAbrirProgAnterior(this, eliminable);
    }//GEN-LAST:event_btnProgAcaAnteriorActionPerformed

    private void mniCrearProgAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCrearProgAcaActionPerformed
        btnProgAcaActionPerformed(evt);
    }//GEN-LAST:event_mniCrearProgAcaActionPerformed

    private void mniModTipologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModTipologiaActionPerformed
        new VentTipologias(modificable, eliminable);
    }//GEN-LAST:event_mniModTipologiaActionPerformed

    private void mniModTipoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModTipoContratoActionPerformed
        new VentModTipoContrato(modificable, eliminable);
    }//GEN-LAST:event_mniModTipoContratoActionPerformed

    private void mniModNivelEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModNivelEstudioActionPerformed
        new VentNivelesEstudio(modificable, eliminable);
    }//GEN-LAST:event_mniModNivelEstudioActionPerformed

    private void mniModEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModEdificioActionPerformed
        new VentEdificios(modificable, eliminable);
    }//GEN-LAST:event_mniModEdificioActionPerformed

    private void mniModPlanEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModPlanEstudioActionPerformed
        new VentModPlanEstudio(modificable, eliminable);
    }//GEN-LAST:event_mniModPlanEstudioActionPerformed

    private void mniModSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModSalonActionPerformed
        new VentSalones(modificable, eliminable);
    }//GEN-LAST:event_mniModSalonActionPerformed

    private void mniVerProgAcaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVerProgAcaAnteriorActionPerformed
        btnProgAcaAnteriorActionPerformed(evt);
    }//GEN-LAST:event_mniVerProgAcaAnteriorActionPerformed

    private void btnAdProgDesdeAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdProgDesdeAnteriorActionPerformed
        new VentCrearProgDesdeAnterior();
    }//GEN-LAST:event_btnAdProgDesdeAnteriorActionPerformed

    private void mniCrearNuevaDesdeAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCrearNuevaDesdeAnteriorActionPerformed
        btnAdProgDesdeAnteriorActionPerformed(evt);
    }//GEN-LAST:event_mniCrearNuevaDesdeAnteriorActionPerformed

    private void mniVincularAsigPlanEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVincularAsigPlanEstudioActionPerformed
        new VentVincularAsigPlanEstudio();
    }//GEN-LAST:event_mniVincularAsigPlanEstudioActionPerformed

    private void mniModAsigPlanEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModAsigPlanEstudioActionPerformed
        new VentPlanEstudio(modificable, eliminable);
    }//GEN-LAST:event_mniModAsigPlanEstudioActionPerformed

    private void mniCambiarPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCambiarPermisosActionPerformed
        new VentPermisos();
    }//GEN-LAST:event_mniCambiarPermisosActionPerformed

    private void mniContenidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniContenidosActionPerformed
        new VentAyuda();
    }//GEN-LAST:event_mniContenidosActionPerformed

    private void mniElegirColoresHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniElegirColoresHorarioActionPerformed
        new VentColoresHorarios();
    }//GEN-LAST:event_mniElegirColoresHorarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdAsig;
    private javax.swing.JButton btnAdDoc;
    private javax.swing.JButton btnAdEdificio;
    private javax.swing.JButton btnAdProgDesdeAnterior;
    private javax.swing.JButton btnAdSalon;
    private javax.swing.JButton btnProgAca;
    private javax.swing.JButton btnProgAcaAnterior;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAsignaturas;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDocentes;
    private javax.swing.JMenu jMenuEdificio;
    private javax.swing.JMenu jMenuEspaciosFisicos;
    private javax.swing.JMenu jMenuImportar;
    private javax.swing.JMenu jMenuModPlanEstudio;
    private javax.swing.JMenu jMenuNivelesEstudio;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenu jMenuPlanesEstudio;
    private javax.swing.JMenu jMenuProgAcad;
    private javax.swing.JMenu jMenuSalon;
    private javax.swing.JMenu jMenuTipologias;
    private javax.swing.JMenu jMenuTiposContrato;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JMenuItem mnINuevoUsua;
    private javax.swing.JMenuItem mniAcercaDe;
    private javax.swing.JMenuItem mniAdAsignatura;
    private javax.swing.JMenuItem mniAdDocente;
    private javax.swing.JMenuItem mniAdEdificio;
    private javax.swing.JMenuItem mniAdNivelEstudio;
    private javax.swing.JMenuItem mniAdPlanEstudio;
    private javax.swing.JMenuItem mniAdSalon;
    private javax.swing.JMenuItem mniAdTipoContrato;
    private javax.swing.JMenuItem mniAdTipologia;
    private javax.swing.JMenuItem mniCambiarCorreo;
    private javax.swing.JMenuItem mniCambiarPass;
    private javax.swing.JMenuItem mniCambiarPermisos;
    private javax.swing.JMenuItem mniContenidos;
    private javax.swing.JMenuItem mniCrearNuevaDesdeAnterior;
    private javax.swing.JMenuItem mniCrearProgAca;
    private javax.swing.JMenuItem mniElegirColoresHorario;
    private javax.swing.JMenuItem mniEliminarUsuarios;
    private javax.swing.JMenuItem mniImpAsignaturas;
    private javax.swing.JMenuItem mniImpDocentes;
    private javax.swing.JMenuItem mniImpPlanEstudios;
    private javax.swing.JMenuItem mniImpSalones;
    private javax.swing.JMenuItem mniImportarProgAca;
    private javax.swing.JMenuItem mniModAsigPlanEstudio;
    private javax.swing.JMenuItem mniModAsignatura;
    private javax.swing.JMenuItem mniModDocente;
    private javax.swing.JMenuItem mniModEdificio;
    private javax.swing.JMenuItem mniModNivelEstudio;
    private javax.swing.JMenuItem mniModPlanEstudio;
    private javax.swing.JMenuItem mniModPrerrequisitos;
    private javax.swing.JMenuItem mniModSalon;
    private javax.swing.JMenuItem mniModTipoContrato;
    private javax.swing.JMenuItem mniModTipologia;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenuItem mniVerProgAcaAnterior;
    private javax.swing.JMenuItem mniVincularAsigPlanEstudio;
    // End of variables declaration//GEN-END:variables

    public void setVentanaProgAca(VentProgAca ventana) {
        jDesktopPane1.add(ventana);
        try {
            ventana.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }
    }

    public boolean getEditable() {
        return creable;
    }

    public boolean getModificable() {
        return modificable;
    }

    public boolean getEliminable() {
        return eliminable;
    }
}
