/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdCrearDocente;
import business.ButtonHandler;
import business.ComboBoxTipoContrato;
import dataDB.Docente;
import dataDB.Tipocontrato;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VentCrearDocente extends JFrame {

    private Docente docente;

    /**
     * Creates new form VentCrearDocente
     */
    public VentCrearDocente() {
        initComponents();
        this.setVisible(true);
    }

    /**
     *
     * @param docente el docente a modificar
     */
    public VentCrearDocente(Docente docente) {
        this.docente = docente;
        initComponents();
        this.setNomDocente(docente.getNombreDocente());
        this.setDocDocente(String.valueOf(docente.getDocumentoDoc()));
        this.setCorreoElec(docente.getCorreoElectronico());
        this.setActivo(docente.getActivo());
        this.setTipoContrato(docente.getIdTipoContrato());
        this.jCkDocenteActivo.setVisible(true);
        this.btnAdDocente.setActionCommand("Modificar");
        this.btnAdDocente.setText("Modificar");
        this.setTitle("Modificar Docente");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomDocente = new javax.swing.JLabel();
        txtNomDocente = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtDocDocente = new javax.swing.JTextField();
        lblTipoContrato = new javax.swing.JLabel();
        cbTipoContrato = new ComboBoxTipoContrato();
        btnAdDocente = new javax.swing.JButton();
        jCkDocenteActivo = new javax.swing.JCheckBox();
        jCkDocenteActivo.setSelected(true);
        jCkDocenteActivo.setVisible(false);
        btnCancelar = new javax.swing.JButton();
        lblCorreoElec = new javax.swing.JLabel();
        txtCorreoElec = new javax.swing.JTextField();
        btnAgregarTipoContrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nuevo docente");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblNomDocente.setText("Nombre:");

        lblId.setText("Identificación:");

        lblTipoContrato.setText("Tipo de contrato:");

        btnAdDocente.addActionListener(new ButtonHandler(new CmdCrearDocente(this, btnAdDocente)));
        btnAdDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnAdDocente.setMnemonic(KeyEvent.VK_ENTER);
        btnAdDocente.setText("Aceptar");

        jCkDocenteActivo.setText("Activo");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCorreoElec.setText("Correo electrónico:");

        btnAgregarTipoContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        btnAgregarTipoContrato.setToolTipText("Agregar nuevo tipo de contrato");
        btnAgregarTipoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnCancelar)
                        .addGap(61, 61, 61)
                        .addComponent(btnAdDocente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorreoElec)
                            .addComponent(lblTipoContrato))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoElec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 82, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCkDocenteActivo)
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblNomDocente))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDocDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomDocente)
                    .addComponent(txtNomDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId)
                    .addComponent(jCkDocenteActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoElec)
                    .addComponent(txtCorreoElec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarTipoContrato)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTipoContrato)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAdDocente))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarTipoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoContratoActionPerformed
        new VentCrearTipoContrato((ComboBoxTipoContrato) cbTipoContrato);
    }//GEN-LAST:event_btnAgregarTipoContratoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdDocente;
    private javax.swing.JButton btnAgregarTipoContrato;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cbTipoContrato;
    private javax.swing.JCheckBox jCkDocenteActivo;
    private javax.swing.JLabel lblCorreoElec;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNomDocente;
    private javax.swing.JLabel lblTipoContrato;
    private javax.swing.JTextField txtCorreoElec;
    private javax.swing.JTextField txtDocDocente;
    private javax.swing.JTextField txtNomDocente;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return el nombre del docente
     */
    public String getNomDocente() {
        return txtNomDocente.getText().toUpperCase();
    }

    /**
     *
     * @return el número de identificación del docente
     */
    public String getDocDocente() {
        return txtDocDocente.getText();
    }

    /**
     *
     * @return el tipo de contrato del docente
     */
    public String getTipoContrato() {
        return cbTipoContrato.getSelectedItem().toString().toUpperCase();
    }

    /**
     *
     * @return el correo electrónico del docente
     */
    public String getCorreoElec() {
        return txtCorreoElec.getText().toUpperCase();
    }

    /**
     *
     * @return el estado : Activo/no activo del docente
     */
    public Boolean getActivo() {
        return jCkDocenteActivo.isSelected();
    }

    /**
     *
     * @param activo el estado: activo / no activo del docente a modificar
     */
    public void setActivo(Boolean activo) {
        this.jCkDocenteActivo.setSelected(activo);
    }

    /**
     *
     * @param correoElec el correo electrónico del docente a modificar
     */
    public void setCorreoElec(String correoElec) {
        this.txtCorreoElec.setText(correoElec);
    }

    /**
     *
     * @param nombre el nombre del docente a modificar
     */
    public void setNomDocente(String nombre) {
        txtNomDocente.setText(nombre);
    }

    /**
     *
     * @param documentoDoc el número de identificación del docente a modificar
     */
    public void setDocDocente(String documentoDoc) {
        txtDocDocente.setText(documentoDoc);
    }

    /**
     *
     * @param tipoC el tipo de contrato del docente a modificar
     */
    public void setTipoContrato(Tipocontrato tipoC) {
        cbTipoContrato.setSelectedItem(tipoC);
    }

    /**
     *
     * @return el docente a modificar
     */
    public Docente getDocente() {
        return this.docente;
    }

    /**
     * Se muestra cuando el docente ha sido agregado exitomasamente
     */
    public void confirmarDocAgregado() {
        JOptionPane.showMessageDialog(this, "Docente agregado exitosamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/GUI/iconos/docente.png")));
        this.setNomDocente("");
        this.setDocDocente("");
        this.setCorreoElec("");
    }

    /**
     * Se muestra cuando el docente ha sido modificado exitosamente
     */
    public void confirmarDocModificado() {
        JOptionPane.showMessageDialog(this, "Docente modificado exitosamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/GUI/iconos/docente.png")));
    }

}
