/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.ComboBoxDocentes;
import business.HorarioDocente;
import business.Observer;
import data.Manejador;
import dataDB.Docente;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.swing.JButton;

/**
 *
 * @author Carlos
 */
public class VentHorarioDocente extends javax.swing.JFrame {

    private String numProgAca;
    private int idProg;

    /**
     * Creates new form VentHorarioDocente
     */
    public VentHorarioDocente(String numProgAca, int idProg) {
        this.numProgAca = numProgAca;
        this.idProg = idProg;
        initComponents();
        setVisible(true);
        setTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDocentes = new ComboBoxDocentes();
        lblDocente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHorarioDocente = new HorarioDocente(idProg);
        jToolBar1 = new BarraHerramientasTabla(jTableHorarioDocente, this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        jComboBoxDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDocentesActionPerformed(evt);
            }
        });

        lblDocente.setText("Docente:");

        ((ComboBoxDocentes)jComboBoxDocentes).register((Observer)jTableHorarioDocente);
        jScrollPane1.setViewportView(jTableHorarioDocente);

        JButton btnEnviarCorreo = new JButton();
        btnEnviarCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/correoGrande.png"))); // NOI18N
        btnEnviarCorreo.setToolTipText("Enviar horario a correo electrónico del Docente");
        btnEnviarCorreo.setFocusable(false);
        btnEnviarCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnviarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCorreoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEnviarCorreo);
        btnEnviarCorreo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        try{
            EntityManager entityM = Manejador.getManejador().gentEntityManager();
            entityM.createNativeQuery("SELECT 'u' FROM mysql.user u WHERE u.User ='"+Manejador.getUsuario()+"' AND u.Create_user_priv ='Y'").getResultList();

        }
        catch(PersistenceException ex){
            btnEnviarCorreo.setEnabled(false);
        }
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lblDocente)
                .addGap(44, 44, 44)
                .addComponent(jComboBoxDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocente)
                    .addComponent(jComboBoxDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDocentesActionPerformed
        setTitulo();
    }//GEN-LAST:event_jComboBoxDocentesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxDocentes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHorarioDocente;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDocente;
    // End of variables declaration//GEN-END:variables
    
    private void setTitulo(){
        String nombreDocente = ((Docente) jComboBoxDocentes.getSelectedItem() == null ? nombreDocente = "" : ((Docente) jComboBoxDocentes.getSelectedItem()).toString());
        setTitle("Horario Docente " + nombreDocente + " - Programación Académica " + numProgAca);
    }
    
    public Docente getDocenteSeleccionado(){
        return (Docente)jComboBoxDocentes.getSelectedItem();
    }
    
    private void btnEnviarCorreoActionPerformed(java.awt.event.ActionEvent evt) {
        new VentFormatoCorreoHorario(jTableHorarioDocente, this, null);
    }

}
