/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdCrearTipoContrato;
import business.ButtonHandler;
import business.ComboBoxTipoContrato;
import business.Observer;
import dataDB.Tipocontrato;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VentCrearTipoContrato extends javax.swing.JFrame {

    private Tipocontrato tipoContrato;
    private ComboBoxTipoContrato cbTipoContrato;

    /**
     * Creates new form VentCrearTipoContrato
     */
    public VentCrearTipoContrato() {
        initComponents();
        this.setVisible(true);
    }

    public VentCrearTipoContrato(ComboBoxTipoContrato cbTipoContrato) {
        this.cbTipoContrato = cbTipoContrato;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoContrato = new javax.swing.JLabel();
        txtTipoContrato = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear tipo de contrato");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblTipoContrato.setText("Tipo de contrato:");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        CmdCrearTipoContrato btnCrearTipoContrato = new CmdCrearTipoContrato(this, btnAceptar);
        btnCrearTipoContrato.register((Observer) cbTipoContrato);
        btnAceptar.addActionListener(new ButtonHandler(btnCrearTipoContrato));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnAceptar.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTipoContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelar)
                        .addGap(55, 55, 55)
                        .addComponent(btnAceptar)))
                .addGap(46, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoContrato)
                    .addComponent(txtTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cerrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblTipoContrato;
    private javax.swing.JTextField txtTipoContrato;
    // End of variables declaration//GEN-END:variables

    public String getNomTipoContrato() {
        return txtTipoContrato.getText().toUpperCase();
    }

    public void setNomTipoContrato(String nomTipoContrato) {
        this.txtTipoContrato.setText(nomTipoContrato);
    }

    public Tipocontrato getTipoContrato() {
        return this.tipoContrato;
    }

    public void setTipoContrato(Tipocontrato tipoContrato) {
        this.tipoContrato = tipoContrato;
        setNomTipoContrato(tipoContrato.getTipoContrato());
        setBtnActionCommand("Modificar");
        setTitle("Modificar tipo de contrato");
    }

    public void setBtnActionCommand(String accion) {
        this.btnAceptar.setActionCommand(accion);
        this.btnAceptar.setText(accion);
    }

    public void cerrar() {
        this.dispose();
    }

    public void confirmarTipoContratoAgregado() {
        JOptionPane.showMessageDialog(this, "Tipo de contrato agregado corrrectamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        this.setNomTipoContrato("");
    }

    public void confirmarTipoContratoModificado() {
        JOptionPane.showMessageDialog(this, "Tipo de contrato modificado corrrectamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    }

    public void errorNombreVacio() {
        JOptionPane.showMessageDialog(this, "Escriba un nombre para el tipo de contrato.", "Error", JOptionPane.ERROR_MESSAGE);
    }

}
