/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import generalities.Errores;
import business.ButtonHandler;
import business.CmdElegirColoresHorarios;
import business.ComboBoxEdificio;
import business.ComboBoxSalon;
import business.ListaAsignaturas;
import business.ComboBoxDocentes;
import business.Horario;
import business.ListaGrupos;
import business.ListaSemestre;
import business.HorarioGrupoAsignatura;
import business.HorarioDocente;
import business.HorarioSalon;
import business.ListaPlanEstudios;
import business.Observable;
import business.Observer;
import data.Manejador;
import dataDB.Asignatura;
import dataDB.Docente;
import dataDB.Edificio;
import dataDB.GrupoPK;
import dataDB.Itemhorario;
import dataDB.Planestudio;
import dataDB.Progacademica;
import dataDB.Salon;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JToolBar;

/**
 *
 * @author Carlos
 */
public class VentProgAca extends javax.swing.JInternalFrame {

    private String numProgAca;
    private int idProg;
    private boolean creable;
    private boolean modificable;
    private boolean eliminable;
    private Itemhorario itemHorarioSeleccionado;
    public static ArrayList<VentProgAca> ventanasProgAca = new ArrayList<>();

    /**
     * Creates new form VentProgAca
     */
    public VentProgAca(String numProgAca, boolean creable, boolean modificable, boolean eliminable) {
        this.numProgAca = numProgAca;
        this.creable = creable;
        this.modificable = modificable;
        this.eliminable = eliminable;
        EntityManager entity = Manejador.getManejador().gentEntityManager();
        idProg = ((Progacademica) (entity.createNamedQuery("Progacademica.findByNumeroProg").setParameter("numeroProg", numProgAca).getSingleResult())).getIdProg();
        initComponents();
        btnModificar.setEnabled(false);
        if (!creable) {
            btnImportarInsc.setEnabled(false);
            btnAgregarGrupo.setEnabled(false);
            btnCrearHorario.setEnabled(false);
            btnCrearHorario.setSelected(false);
        }
        if (!eliminable) {
            btnEliminarGrupo.setEnabled(false);
        }
        this.title = "Edición de Programación Académica - " + String.valueOf(numProgAca);
        
        ventanasProgAca.add(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnHorarioPorDocente = new javax.swing.JButton();
        btnHorarioPorSalon = new javax.swing.JButton();
        btnHorarioPorSemestre = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnImportarInsc = new javax.swing.JButton();
        btnVerInscritos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnExportarProgra = new javax.swing.JButton();
        btnExportarHorariosProfs = new javax.swing.JButton();
        btnExportarHorariosSalones = new javax.swing.JButton();
        btnEnviarTodosHorariosCorreo = new JButton();
        lblPlanEstudio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPlanEstudios = new business.ListaPlanEstudios();
        lblSemestre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSemestre = new business.ListaSemestre();
        lblAsignaturas = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAsignaturas = new ListaAsignaturas((ListaPlanEstudios)jListPlanEstudios);
        lblGrupos = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListGrupos = new ListaGrupos(this.numProgAca);
        btnAgregarGrupo = new javax.swing.JButton();
        btnEliminarGrupo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableHorarioSalon = new HorarioSalon(idProg);
        lblHorarioDocente = new javax.swing.JLabel();
        lblHorarioSalon = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableHorarioDocente = new HorarioDocente(idProg);
        lbl1Grupo = new javax.swing.JLabel();
        lbl2Grupos = new javax.swing.JLabel();
        lbl3Grupos = new javax.swing.JLabel();
        lbl4Grupos = new javax.swing.JLabel();
        lbl5MasGrupos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableHorarioAsigna = new business.HorarioGrupoAsignatura(idProg, eliminable, this);
        lblHorarioAsignatura = new javax.swing.JLabel();
        lblLimiteMax = new javax.swing.JLabel();
        txtLimiteMax = new javax.swing.JTextField();
        lblCuotas = new javax.swing.JLabel();
        txtCuotas = new javax.swing.JTextField();
        lblCapacidadMax = new javax.swing.JLabel();
        txtCapMax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCapMin = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblDocente = new javax.swing.JLabel();
        jComboBoxDocentes = new ComboBoxDocentes();
        lblEdificio = new javax.swing.JLabel();
        jComboBoxEdificio = new ComboBoxEdificio();
        jComboBoxSalon = new ComboBoxSalon();
        lblSalon = new javax.swing.JLabel();
        jRadioButtonAsistente = new javax.swing.JRadioButton();
        jRadioButtonPrincipal = new javax.swing.JRadioButton();
        btnCrearHorario = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png"))); // NOI18N
        setVisible(true);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(JToolBar.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setAutoscrolls(true);

        btnHorarioPorDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/HorarioPorDocente.png"))); // NOI18N
        btnHorarioPorDocente.setMnemonic(KeyEvent.VK_O);
        btnHorarioPorDocente.setToolTipText("Horario por docente (ALT + O)");
        btnHorarioPorDocente.setFocusable(false);
        btnHorarioPorDocente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHorarioPorDocente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHorarioPorDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioPorDocenteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHorarioPorDocente);

        btnHorarioPorSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/HorarioPorSalon .png"))); // NOI18N
        btnHorarioPorSalon.setMnemonic(KeyEvent.VK_S);
        btnHorarioPorSalon.setToolTipText("Horario por salón(ALT + S)");
        btnHorarioPorSalon.setFocusable(false);
        btnHorarioPorSalon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHorarioPorSalon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHorarioPorSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioPorSalonActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHorarioPorSalon);

        btnHorarioPorSemestre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/HorarioPorSemestre.png"))); // NOI18N
        btnHorarioPorSemestre.setMnemonic(KeyEvent.VK_E);
        btnHorarioPorSemestre.setToolTipText("Horario por semestre (ALT + E)");
        btnHorarioPorSemestre.setFocusable(false);
        btnHorarioPorSemestre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHorarioPorSemestre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHorarioPorSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioPorSemestreActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHorarioPorSemestre);
        jToolBar1.add(jSeparator1);

        btnImportarInsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/importarGrande.png"))); // NOI18N
        btnImportarInsc.setToolTipText("Importar inscritos");
        btnImportarInsc.setFocusable(false);
        btnImportarInsc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImportarInsc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImportarInsc.addActionListener(new ButtonHandler(new business.CmdImportarInscritos(numProgAca)));
        jToolBar1.add(btnImportarInsc);

        btnVerInscritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/verInscritos.png"))); // NOI18N
        btnVerInscritos.setToolTipText("Ver inscritos");
        btnVerInscritos.setFocusable(false);
        btnVerInscritos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerInscritos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerInscritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerInscritosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerInscritos);
        jToolBar1.add(jSeparator2);

        btnExportarProgra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/PrograExportar.png"))); // NOI18N
        btnExportarProgra.setToolTipText("Exportar programación académica");
        btnExportarProgra.setFocusable(false);
        btnExportarProgra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportarProgra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportarProgra.addActionListener(new ButtonHandler(new business.CmdExportarProgAca(this)));
        jToolBar1.add(btnExportarProgra);

        btnExportarHorariosProfs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/exportarHorProfs.png"))); // NOI18N
        btnExportarHorariosProfs.setToolTipText("Exportar horarios de Docentes");
        btnExportarHorariosProfs.setFocusable(false);
        btnExportarHorariosProfs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportarHorariosProfs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportarHorariosProfs.addActionListener(new ButtonHandler(new business.CmdExportarHorariosDocentes(this)));
        jToolBar1.add(btnExportarHorariosProfs);

        btnExportarHorariosSalones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/exportarHorSalones.png"))); // NOI18N
        btnExportarHorariosSalones.setToolTipText("Exportar horarios de salones");
        btnExportarHorariosSalones.setFocusable(false);
        btnExportarHorariosSalones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportarHorariosSalones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportarHorariosSalones.addActionListener(new ButtonHandler(new business.CmdExportarHorariosSalones(this)));
        jToolBar1.add(btnExportarHorariosSalones);

        btnEnviarTodosHorariosCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/correoGrande.png"))); // NOI18N
        btnEnviarTodosHorariosCorreo.setFocusable(false);
        btnEnviarTodosHorariosCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnviarTodosHorariosCorreo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnviarTodosHorariosCorreo.setToolTipText("Enviar a todos los Docentes su respectivo horario de la programación académica actual");
        btnEnviarTodosHorariosCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarTodosHorariosCorreoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEnviarTodosHorariosCorreo);
        try{
            EntityManager entityM = Manejador.getManejador().gentEntityManager();
            entityM.createNativeQuery("SELECT 'u' FROM mysql.user u WHERE u.User ='"+Manejador.getUsuario()+"' AND u.Create_user_priv ='Y'").getResultList();

        }
        catch(PersistenceException ex){
            btnEnviarTodosHorariosCorreo.setEnabled(false);
        }

        lblPlanEstudio.setText("Plan de estudios:");

        jListPlanEstudios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListPlanEstudios);

        lblSemestre.setText("Semestre:");

        ((business.ListaPlanEstudios)jListPlanEstudios).register((business.ListaSemestre)jListSemestre);
        jScrollPane2.setViewportView(jListSemestre);

        lblAsignaturas.setText("Asignaturas:");

        ((ListaSemestre) jListSemestre).register((ListaAsignaturas)jListAsignaturas);
        jScrollPane3.setViewportView(jListAsignaturas);

        lblGrupos.setText("Grupos:");

        ((ListaAsignaturas) jListAsignaturas).register((ListaGrupos)jListGrupos);
        jScrollPane5.setViewportView(jListGrupos);

        business.CmdAgregarGrupo btnAgGrupo = new business.CmdAgregarGrupo((ListaGrupos)jListGrupos);
        btnAgregarGrupo.addActionListener(new ButtonHandler(btnAgGrupo));
        btnAgregarGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        btnAgregarGrupo.setMnemonic(KeyEvent.VK_PLUS);
        btnAgregarGrupo.setToolTipText("Crear grupo(Alt+ +)");

        business.CmdEliminarGrupo btnElimGr = new business.CmdEliminarGrupo((ListaGrupos)jListGrupos);
        btnEliminarGrupo.addActionListener(new ButtonHandler(btnElimGr));
        btnEliminarGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnEliminarGrupo.setMnemonic(KeyEvent.VK_MINUS);
        btnEliminarGrupo.setToolTipText("Eliminar grupo(Alt + -)");

        ((ComboBoxSalon)jComboBoxSalon).register((Observer)jTableHorarioSalon);
        jScrollPane7.setViewportView(jTableHorarioSalon);

        lblHorarioDocente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHorarioDocente.setText("HORARIO ACTUAL DEL DOCENTE");

        lblHorarioSalon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHorarioSalon.setText("HORARIO ACTUAL DEL SALÓN");

        ((ComboBoxDocentes)jComboBoxDocentes).register((Observer)jTableHorarioDocente);
        jScrollPane4.setViewportView(jTableHorarioDocente);

        lbl1Grupo.setBackground(Horario.UN_GRUPO);
        lbl1Grupo.setText("1 Grupo");
        lbl1Grupo.setOpaque(true);

        lbl2Grupos.setBackground(Horario.DOS_GRUPOS);
        lbl2Grupos.setText("2 Grupos");
        lbl2Grupos.setOpaque(true);

        lbl3Grupos.setBackground(Horario.TRES_GRUPOS);
        lbl3Grupos.setText("3 Grupos");
        lbl3Grupos.setOpaque(true);

        lbl4Grupos.setBackground(Horario.CUATRO_GRUPOS);
        lbl4Grupos.setText("4 Grupos");
        lbl4Grupos.setOpaque(true);

        lbl5MasGrupos.setBackground(Horario.CINCO_GRUPOS);
        lbl5MasGrupos.setText("5 o más Grupos");
        lbl5MasGrupos.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(lblHorarioSalon)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl1Grupo)
                        .addGap(40, 40, 40)
                        .addComponent(lbl2Grupos)
                        .addGap(50, 50, 50)
                        .addComponent(lbl3Grupos)
                        .addGap(47, 47, 47)
                        .addComponent(lbl4Grupos)
                        .addGap(46, 46, 46)
                        .addComponent(lbl5MasGrupos)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(lblHorarioDocente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblHorarioSalon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1Grupo)
                    .addComponent(lbl2Grupos)
                    .addComponent(lbl3Grupos)
                    .addComponent(lbl4Grupos)
                    .addComponent(lbl5MasGrupos))
                .addGap(18, 18, 18)
                .addComponent(lblHorarioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        ((business.HorarioGrupoAsignatura)jTableHorarioAsigna).register((Observer)jTableHorarioSalon);
        ((business.HorarioGrupoAsignatura)jTableHorarioAsigna).register((Observer)jTableHorarioDocente);
        ((ListaGrupos)jListGrupos).register((Observer)jTableHorarioAsigna);
        jTableHorarioAsigna.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableHorarioAsigna.setAutoscrolls(false);
        jScrollPane6.setViewportView(jTableHorarioAsigna);

        lblHorarioAsignatura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHorarioAsignatura.setText("HORARIO ACTUAL DEL GRUPO ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblHorarioAsignatura)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHorarioAsignatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        lblLimiteMax.setText("Límite máximo:");

        lblCuotas.setText("Cuotas:");

        lblCapacidadMax.setText("Capacidad máxima:");

        jLabel1.setText("Capacidad mínima:");

        lblDocente.setText("Docente:");

        lblEdificio.setText("Edificio:");

        ((ComboBoxEdificio)jComboBoxEdificio).register((Observer)jComboBoxSalon);

        lblSalon.setText("Salón:");

        jRadioButtonAsistente.setText("Asistente");

        jRadioButtonPrincipal.setText("Principal");
        buttonGroup.add(jRadioButtonAsistente);
        buttonGroup.add(jRadioButtonPrincipal);
        jRadioButtonPrincipal.setSelected(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEdificio)
                    .addComponent(jComboBoxEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalon))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDocente)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jRadioButtonPrincipal)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAsistente)))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addComponent(jComboBoxDocentes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSalon)
                        .addComponent(lblDocente))
                    .addComponent(lblEdificio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAsistente)
                    .addComponent(jRadioButtonPrincipal))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnCrearHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/progAca1.png"))); // NOI18N
        btnCrearHorario.setMnemonic(KeyEvent.VK_C);
        btnCrearHorario.setText("Crear");
        btnCrearHorario.setToolTipText("Crear item de horario (Alt+C)");
        btnCrearHorario.addActionListener(new ButtonHandler(new business.CmdCrearItemHorario(this, btnCrearHorario)));
        btnCrearHorario.setSelected(true);

        btnModificar.addActionListener(new ButtonHandler(new business.CmdModItemHorario(this, btnModificar, Errores.MODIFICAR)));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/modItemHorario.png"))); // NOI18N
        btnModificar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificar)
                                    .addComponent(btnCrearHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblLimiteMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLimiteMax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblCuotas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblCapacidadMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCapMax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCapMin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlanEstudio)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSemestre)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAsignaturas)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGrupos)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEliminarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 29, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPlanEstudio)
                                    .addComponent(lblSemestre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAsignaturas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGrupos)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(btnAgregarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(btnEliminarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane5)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLimiteMax)
                            .addComponent(txtLimiteMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCuotas)
                            .addComponent(txtCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCapacidadMax)
                            .addComponent(txtCapMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtCapMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnCrearHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHorarioPorDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioPorDocenteActionPerformed
        new VentHorarioDocente(numProgAca, idProg);
    }//GEN-LAST:event_btnHorarioPorDocenteActionPerformed

    private void btnHorarioPorSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioPorSalonActionPerformed
        new VentHorarioSalon(numProgAca, idProg);
    }//GEN-LAST:event_btnHorarioPorSalonActionPerformed

    private void btnHorarioPorSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioPorSemestreActionPerformed
        new VentHorarioSemestre(numProgAca, idProg);
    }//GEN-LAST:event_btnHorarioPorSemestreActionPerformed

    private void btnVerInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInscritosActionPerformed
        new VentVerInscritos(numProgAca);
    }//GEN-LAST:event_btnVerInscritosActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarGrupo;
    private javax.swing.JButton btnCrearHorario;
    private javax.swing.JButton btnEliminarGrupo;
    private javax.swing.JButton btnEnviarTodosHorariosCorreo;
    private javax.swing.JButton btnExportarHorariosProfs;
    private javax.swing.JButton btnExportarHorariosSalones;
    private javax.swing.JButton btnExportarProgra;
    private javax.swing.JButton btnHorarioPorDocente;
    private javax.swing.JButton btnHorarioPorSalon;
    private javax.swing.JButton btnHorarioPorSemestre;
    private javax.swing.JButton btnImportarInsc;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVerInscritos;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox jComboBoxDocentes;
    private javax.swing.JComboBox jComboBoxEdificio;
    private javax.swing.JComboBox jComboBoxSalon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListAsignaturas;
    private javax.swing.JList jListGrupos;
    private javax.swing.JList jListPlanEstudios;
    private javax.swing.JList jListSemestre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButtonAsistente;
    private javax.swing.JRadioButton jRadioButtonPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTable jTableHorarioAsigna;
    private javax.swing.JTable jTableHorarioDocente;
    private javax.swing.JTable jTableHorarioSalon;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl1Grupo;
    private javax.swing.JLabel lbl2Grupos;
    private javax.swing.JLabel lbl3Grupos;
    private javax.swing.JLabel lbl4Grupos;
    private javax.swing.JLabel lbl5MasGrupos;
    private javax.swing.JLabel lblAsignaturas;
    private javax.swing.JLabel lblCapacidadMax;
    private javax.swing.JLabel lblCuotas;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblEdificio;
    private javax.swing.JLabel lblGrupos;
    private javax.swing.JLabel lblHorarioAsignatura;
    private javax.swing.JLabel lblHorarioDocente;
    private javax.swing.JLabel lblHorarioSalon;
    private javax.swing.JLabel lblLimiteMax;
    private javax.swing.JLabel lblPlanEstudio;
    private javax.swing.JLabel lblSalon;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JTextField txtCapMax;
    private javax.swing.JTextField txtCapMin;
    private javax.swing.JTextField txtCuotas;
    private javax.swing.JTextField txtLimiteMax;
    // End of variables declaration//GEN-END:variables

    private void btnEnviarTodosHorariosCorreoActionPerformed(java.awt.event.ActionEvent evt) {
        new VentFormatoCorreoHorario(null, null, this);
    }

    public Planestudio getPlanEstudios() {
        return (Planestudio) jListPlanEstudios.getSelectedValue();
    }

    public Asignatura getAsignatura() {
        return (Asignatura) jListAsignaturas.getSelectedValue();
    }

    public GrupoPK getGrupoPK() {
        return (GrupoPK) jListGrupos.getSelectedValue();
    }

    public Edificio getEdificio() {
        return (Edificio) jComboBoxEdificio.getSelectedItem();
    }

    public void setEdificio(Edificio edificio) {
        jComboBoxEdificio.setSelectedItem(edificio);
        jComboBoxEdificio.setEnabled(false);
    }

    public Docente getDocente() {
        return (Docente) jComboBoxDocentes.getSelectedItem();
    }

    public void setDocente(Docente docente) {
        jComboBoxDocentes.setSelectedItem(docente);
        jComboBoxDocentes.setEnabled(false);
    }

    public Salon getSalon() {
        return (Salon) jComboBoxSalon.getSelectedItem();
    }

    public void setSalon(Salon salon) {
        jComboBoxSalon.setSelectedItem(salon);
        jComboBoxSalon.setEnabled(false);
    }

    public String getDia() {
        return ((HorarioGrupoAsignatura) jTableHorarioAsigna).getNombreDia();
    }

    public int getHoraInicio() {
        return ((HorarioGrupoAsignatura) jTableHorarioAsigna).getNumeroHora();
    }

    public String getNumeroProg() {
        return numProgAca;
    }

    public int getIdProg() {
        return idProg;
    }

    public HorarioDocente getTablaHorarioDocente() {
        return (HorarioDocente) jTableHorarioDocente;
    }

    public HorarioSalon getTablaHorarioSalon() {
        return (HorarioSalon) jTableHorarioSalon;
    }

    public HorarioGrupoAsignatura getTablaHorarioAsignatura() {
        return (HorarioGrupoAsignatura) jTableHorarioAsigna;
    }

    public void actualizarHorarios() {
        ((Horario) jTableHorarioDocente).actualizarDatos((Observable) jComboBoxDocentes);
        ((Horario) jTableHorarioSalon).actualizarDatos((Observable) jComboBoxSalon);
        ((Horario) jTableHorarioAsigna).actualizarDatos((Observable) jListGrupos);
    }

    public int getLimiteMax() {
        return Integer.parseInt(txtLimiteMax.getText());
    }

    public void setLimiteMax(String limiteMax) {
        txtLimiteMax.setText(limiteMax);
        txtLimiteMax.setEditable(false);
    }

    public int getCuotas() {
        return Integer.parseInt(txtCuotas.getText());
    }

    public void setCuotas(String cuotas) {
        txtCuotas.setText(cuotas);
        txtCuotas.setEditable(false);
    }

    public int getCapMax() {
        return Integer.parseInt(txtCapMax.getText());
    }

    public void setCapMax(String capMax) {
        txtCapMax.setText(capMax);
        txtCapMax.setEditable(false);
    }

    public int getCapMin() {
        return Integer.parseInt(txtCapMin.getText());
    }

    public void setCapMin(String capMin) {
        txtCapMin.setText(capMin);
        txtCapMin.setEditable(false);
    }

    public boolean getOpcPrincipal() {
        return jRadioButtonPrincipal.isSelected();
    }

    public void setOpcPrincipal(boolean seleccionado) {
        jRadioButtonPrincipal.setSelected(seleccionado);
        setOpcAsistente(!seleccionado);
        jRadioButtonPrincipal.setEnabled(false);
    }

    public boolean getOpcAsistente() {
        return jRadioButtonAsistente.isSelected();
    }

    public void setOpcAsistente(boolean seleccionado) {
        jRadioButtonAsistente.setSelected(seleccionado);
        jRadioButtonAsistente.setEnabled(false);
    }

    public Itemhorario getItemHorarioSeleccionado() {
        return itemHorarioSeleccionado;
    }

    public void cambiarBtnCrearAAceptarModificar(boolean aceptar) {
        if (aceptar) {
            btnCrearHorario.setActionCommand("Modificar");
            btnCrearHorario.setText("Aceptar");
            btnCrearHorario.setToolTipText("Guardar la modificación");
            btnCrearHorario.setIcon(new ImageIcon(VentProgAca.class.getResource("/GUI/iconos/aceptar.png")));
            btnCrearHorario.setEnabled(true);
            btnCrearHorario.setSelected(true);
            itemHorarioSeleccionado = ((HorarioGrupoAsignatura) jTableHorarioAsigna).getItemHorarioSeleccionado();
        } else {
            btnCrearHorario.setActionCommand("Crear");
            btnCrearHorario.setText("Crear");
            btnCrearHorario.setToolTipText("Crear item de horario (Alt+C)");
            btnCrearHorario.setIcon(new ImageIcon(VentProgAca.class.getResource("/GUI/iconos/progAca1.png")));
        }
    }

    public void habilitarCamposEdicion() {
        txtCapMax.setEditable(true);
        txtCapMin.setEditable(true);
        txtCuotas.setEditable(true);
        txtLimiteMax.setEditable(true);
        jRadioButtonAsistente.setEnabled(true);
        jRadioButtonPrincipal.setEnabled(true);
        jComboBoxDocentes.setEnabled(true);
        jComboBoxEdificio.setEnabled(true);
        jComboBoxSalon.setEnabled(true);
    }

    public void activarBotonModificar(boolean valor) {

        if (creable && !valor) {
            btnCrearHorario.setActionCommand("Crear");
            btnCrearHorario.setText("Crear");
            btnCrearHorario.setToolTipText("Crear item de horario (Alt+C)");
            btnCrearHorario.setIcon(new ImageIcon(VentProgAca.class.getResource("/GUI/iconos/progAca1.png")));
            btnModificar.setEnabled(valor);
            btnModificar.setSelected(valor);
            btnCrearHorario.setEnabled(!valor);
            btnCrearHorario.setSelected(!valor);
        } else if (modificable && valor) {
            btnModificar.setEnabled(valor);
            btnModificar.setSelected(valor);
            btnModificar.setText("Modificar");
            btnModificar.setActionCommand("Modificar");
            btnModificar.setToolTipText("Modificar item de horario");
            btnModificar.setIcon(new ImageIcon(VentProgAca.class.getResource("/GUI/iconos/modItemHorario.png")));
            btnCrearHorario.setEnabled(!valor);
            btnCrearHorario.setSelected(!valor);

            if (eliminable) {
                btnCrearHorario.setActionCommand("Eliminar");
                btnCrearHorario.setText("Eliminar");
                btnCrearHorario.setToolTipText("Eliminar item de horario (Supr)");
                btnCrearHorario.setIcon(new ImageIcon(VentProgAca.class.getResource("/GUI/iconos/eliminar.png")));
                btnModificar.setEnabled(valor);
                btnModificar.setSelected(valor);
                btnCrearHorario.setEnabled(valor);
                btnCrearHorario.setSelected(valor);
            }
        } else if (modificable && !valor) {
            btnModificar.setEnabled(valor);
            btnModificar.setSelected(valor);
            btnCrearHorario.setEnabled(valor);
            btnCrearHorario.setSelected(valor);

        } else if (creable && valor) {
            btnModificar.setEnabled(!valor);
            btnModificar.setSelected(!valor);
            btnCrearHorario.setEnabled(!valor);
            btnCrearHorario.setSelected(!valor);
        }
    }

    public static void actualizarColoresHorarios() {
        Horario.inicializarColores();
        for (VentProgAca ventProgAca : ventanasProgAca) {
            ventProgAca.lbl1Grupo.setBackground(Horario.UN_GRUPO);
            ventProgAca.lbl2Grupos.setBackground(Horario.DOS_GRUPOS);
            ventProgAca.lbl3Grupos.setBackground(Horario.TRES_GRUPOS);
            ventProgAca.lbl4Grupos.setBackground(Horario.CUATRO_GRUPOS);
            ventProgAca.lbl5MasGrupos.setBackground(Horario.CINCO_GRUPOS);
            ventProgAca.jTableHorarioAsigna.repaint();
            ventProgAca.jTableHorarioDocente.repaint();
            ventProgAca.jTableHorarioSalon.repaint();
        }
    }
}
