/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdEliminarEdificio;
import business.CmdModEdificio;
import business.ButtonHandler;
import business.JChkVerOcultos;
import business.TablaEdificios;

/**
 *
 * @author Carlos
 */
public class VentEdificios extends VentTabla {

    /**
     * Creates new form VentEdificios
     */
    public VentEdificios(boolean editable, boolean eliminable) {
        super(editable, eliminable);
        initComponents();
        inicializarBotones(editable, eliminable);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new TablaEdificios();
        btnModificar = new javax.swing.JButton();
        jToolBar1 = new BarraHerramientasTabla(tabla, this);
        btnEliminar = new javax.swing.JButton();
        jChkVerOcultos = new JChkVerOcultos(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edificios");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());

        jScrollPane1.setAutoscrolls(true);

        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabla);

        btnModificar.addActionListener(new ButtonHandler(new CmdModEdificio(this)));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/editarPeque.png"))); // NOI18N
        btnModificar.setText("Modificar");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnEliminar.addActionListener(new ButtonHandler(new CmdEliminarEdificio(this, btnEliminar)));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnEliminar.setText("Ocultar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jChkVerOcultos)
                        .addGap(112, 112, 112)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(jChkVerOcultos))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /*
    private javax.swing.JButton btnEliminar;
    */
    /*
    private javax.swing.JButton btnModificar;
    */
    /*
    private javax.swing.JCheckBox jChkVerOcultos;
    */
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    /*
    private javax.swing.JTable tabla;
    */
    // End of variables declaration//GEN-END:variables

    public String getSeleccionado() {
        try {
            return (String) tabla.getValueAt(tabla.getSelectedRow(), 0);
        } catch (IndexOutOfBoundsException ex) {
            return null;
        }
    }

    public void removerFila() {
        ((TablaEdificios) tabla).removerFila();
    }
}
