/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.ComboBoxEdificio;
import business.ComboBoxSalon;
import business.HorarioSalon;
import business.Observer;
import dataDB.Edificio;
import dataDB.Salon;

/**
 *
 * @author Carlos
 */
public class VentHorarioSalon extends javax.swing.JFrame {

    private String numProgAca;
    private int idProg;
    /**
     * Creates new form VentHorarioSalon
     */
    public VentHorarioSalon(String numProgAca, int idProg) {
        this.numProgAca = numProgAca;
        this.idProg = idProg;
        initComponents();
        setVisible(true);
        setTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEdificio = new javax.swing.JLabel();
        jComboBoxEdificios = new ComboBoxEdificio();
        lblSalon = new javax.swing.JLabel();
        jComboBoxSalon = new ComboBoxSalon();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHorarioSalon = new HorarioSalon(idProg);
        jToolBar1 = new BarraHerramientasTabla(jTableHorarioSalon, this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Horario por salón");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblEdificio.setText("Edificio:");

        jComboBoxEdificios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEdificiosActionPerformed(evt);
            }
        });

        lblSalon.setText("Salón:");

        ((ComboBoxEdificio)jComboBoxEdificios).register((Observer)jComboBoxSalon);
        jComboBoxSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSalonActionPerformed(evt);
            }
        });

        ((ComboBoxSalon)jComboBoxSalon).register((Observer)jTableHorarioSalon);
        jScrollPane1.setViewportView(jTableHorarioSalon);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblEdificio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxEdificios, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(lblSalon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdificio)
                    .addComponent(jComboBoxEdificios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalon)
                    .addComponent(jComboBoxSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEdificiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEdificiosActionPerformed
        setTitulo();
    }//GEN-LAST:event_jComboBoxEdificiosActionPerformed

    private void jComboBoxSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSalonActionPerformed
        setTitulo();
    }//GEN-LAST:event_jComboBoxSalonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxEdificios;
    private javax.swing.JComboBox jComboBoxSalon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHorarioSalon;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEdificio;
    private javax.swing.JLabel lblSalon;
    // End of variables declaration//GEN-END:variables
    
    private void setTitulo(){
        String salon = (Salon)jComboBoxSalon.getSelectedItem() == null ? salon = "" : ((Salon) (jComboBoxSalon.getSelectedItem())).toString();
        String edificio = (Edificio) jComboBoxEdificios.getSelectedItem() == null ? edificio = "" : ((Edificio) jComboBoxEdificios.getSelectedItem()).toString();
        setTitle("Horario Salón " + salon + " Edificio " + edificio + " - Programación Académica " + numProgAca);
    }

}
