/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdCrearTipologia;
import business.ButtonHandler;
import business.ComboBoxTipologia;
import business.Observer;
import dataDB.Tipologia;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VentCrearTipologia extends javax.swing.JFrame {

    private Tipologia tip;
    private ComboBoxTipologia cbTipologia;

    /**
     * Creates new form VentCrearTipologia
     */
    public VentCrearTipologia() {
        initComponents();
        this.setVisible(true);
    }

    public VentCrearTipologia(ComboBoxTipologia cbTipologia) {
        this.cbTipologia = cbTipologia;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCrearNuevaTipologia = new javax.swing.JLabel();
        txtNomTipologia = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        CmdCrearTipologia btnCrearTipologia = new CmdCrearTipologia(this, btnAceptar);
        btnCrearTipologia.register((Observer) cbTipologia);
        btnAceptar.addActionListener(new ButtonHandler(btnCrearTipologia));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nueva tipología");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblCrearNuevaTipologia.setText("Nombre tipología:");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnAceptar.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCrearNuevaTipologia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomTipologia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrearNuevaTipologia)
                    .addComponent(txtNomTipologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cerrar();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCrearNuevaTipologia;
    private javax.swing.JTextField txtNomTipologia;
    // End of variables declaration//GEN-END:variables

    public String getNomTipologia() {
        return txtNomTipologia.getText().toUpperCase();
    }

    public void setNomTipologia(String nomTipologia) {
        this.txtNomTipologia.setText(nomTipologia);
    }

    public void cerrar() {
        this.dispose();
    }

    public void confirmarTipologiaAgregada() {
        JOptionPane.showMessageDialog(this, "Tipología agregada correctamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        this.setNomTipologia("");
    }

    public void setBtnActionCommand(String accion) {
        this.btnAceptar.setActionCommand(accion);
        this.btnAceptar.setText(accion);
    }

    public Tipologia getTipologia() {
        return this.tip;
    }

    public void setTipologia(Tipologia tip) {
        this.tip = tip;
        setNomTipologia(tip.getTipologia());
        setBtnActionCommand("Modificar");
        setTitle("Modificar tipología");
    }

    public void confirmarTipologiaModificada() {
        JOptionPane.showMessageDialog(this, "Tipología modificada correctamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    }
}
