/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import generalities.Errores;
import business.CmdAgregarSemestre;
import business.CmdVincularAsigPlanEstudio;
import business.ButtonHandler;
import business.ComboBoxAsignaturas;
import business.ComboBoxNumSemestre;
import business.ComboBoxPlanEstudios;
import business.ComboBoxTipologia;
import dataDB.Asignatura;
import dataDB.Asignaturaenplanestudio;
import dataDB.Planestudio;
import dataDB.Semestre;
import dataDB.Tipologia;

/**
 *
 * @author Carlos
 */
public class VentVincularAsigPlanEstudio extends javax.swing.JFrame {

    private Asignaturaenplanestudio asignaturaEnPlan;

    /**
     * Creates new form VentVincularAsigPlanEstudio
     */
    public VentVincularAsigPlanEstudio() {
        initComponents();
        setVisible(true);
        if (jcbAsignaturas.getItemCount() == 0 || jcbPlanEstudio.getItemCount() == 0 || jcbTipologia.getItemCount() == 0 || jcbNumSemestre.getItemCount() == 0) {
            btnAceptar.setEnabled(false);
        }
    }

    public VentVincularAsigPlanEstudio(Asignaturaenplanestudio asignaturaEnPlan) {
        this.asignaturaEnPlan = asignaturaEnPlan;
        initComponents();
        jcbAsignaturas.setSelectedItem(asignaturaEnPlan.getAsignatura());
        jcbAsignaturas.setEnabled(false);
        jcbPlanEstudio.setSelectedItem(asignaturaEnPlan.getPlanestudio());
        jcbPlanEstudio.setEnabled(false);
        jcbNumSemestre.setSelectedItem(asignaturaEnPlan.getSemestre());
        jcbTipologia.setSelectedItem(asignaturaEnPlan.getIdTipologia());
        btnAceptar.setActionCommand("Modificar");
        btnAceptar.setText("Modificar");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarPlanEstudio = new javax.swing.JButton();
        btnAgregarTipologia = new javax.swing.JButton();
        lblPlanEstudio = new javax.swing.JLabel();
        jcbPlanEstudio = new ComboBoxPlanEstudios();
        lblSemestre = new javax.swing.JLabel();
        jcbNumSemestre = new ComboBoxNumSemestre();
        jcbTipologia = new ComboBoxTipologia();
        lblTipologia = new javax.swing.JLabel();
        btnAdSemestre = new javax.swing.JButton();
        lblAsignatura = new javax.swing.JLabel();
        jcbAsignaturas = new ComboBoxAsignaturas();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vincular asignatura a plan de estudio");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        btnAgregarPlanEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        btnAgregarPlanEstudio.setToolTipText("Agregar nuevo plan de estudio");
        btnAgregarPlanEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPlanEstudioActionPerformed(evt);
            }
        });

        btnAgregarTipologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        btnAgregarTipologia.setToolTipText("Agregar nueva tipología");
        btnAgregarTipologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipologiaActionPerformed(evt);
            }
        });

        lblPlanEstudio.setText("Plan de estudio:");

        lblSemestre.setText("Número de semestre:");

        lblTipologia.setText("Tipología:");

        btnAdSemestre.addActionListener(new ButtonHandler(new CmdAgregarSemestre(this)));
        btnAdSemestre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        btnAdSemestre.setToolTipText("Agregar semestre");

        lblAsignatura.setText("Asignatura:");

        btnAceptar.addActionListener(new ButtonHandler(new CmdVincularAsigPlanEstudio(this, Errores.CREAR)));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnAceptar.setText("Aceptar");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSemestre)
                            .addComponent(lblPlanEstudio)
                            .addComponent(lblTipologia)
                            .addComponent(lblAsignatura))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbAsignaturas, 0, 290, Short.MAX_VALUE)
                                    .addComponent(jcbPlanEstudio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbTipologia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAgregarTipologia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbNumSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAdSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsignatura)
                    .addComponent(jcbAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTipologia)
                        .addComponent(jcbTipologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregarTipologia))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblPlanEstudio))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAgregarPlanEstudio))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jcbPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdSemestre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSemestre)
                        .addComponent(jcbNumSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPlanEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlanEstudioActionPerformed
        new VentCrearPlanEstudio((ComboBoxPlanEstudios) jcbPlanEstudio);
    }//GEN-LAST:event_btnAgregarPlanEstudioActionPerformed

    private void btnAgregarTipologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipologiaActionPerformed
        new VentCrearTipologia((ComboBoxTipologia) jcbTipologia);
    }//GEN-LAST:event_btnAgregarTipologiaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAdSemestre;
    private javax.swing.JButton btnAgregarPlanEstudio;
    private javax.swing.JButton btnAgregarTipologia;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox jcbAsignaturas;
    private javax.swing.JComboBox jcbNumSemestre;
    private javax.swing.JComboBox jcbPlanEstudio;
    private javax.swing.JComboBox jcbTipologia;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblPlanEstudio;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JLabel lblTipologia;
    // End of variables declaration//GEN-END:variables

    public Planestudio getPlanEstudio() {
        return (Planestudio) jcbPlanEstudio.getSelectedItem();
    }

    public Tipologia getTipologia() {
        return (Tipologia) jcbTipologia.getSelectedItem();
    }

    public void setPlanEstudio(Planestudio plan) {
        jcbPlanEstudio.setSelectedItem(plan);
    }

    public void setTipologia(Tipologia tipologia) {
        jcbTipologia.setSelectedItem(tipologia);
    }

    public Asignatura getAsignatura() {
        return (Asignatura) jcbAsignaturas.getSelectedItem();
    }

    public void setAsignatura(Asignatura asignatura) {
        jcbAsignaturas.setSelectedItem(asignatura);
    }

    public Semestre getSemestre() {
        return (Semestre) jcbNumSemestre.getSelectedItem();
    }

    public void setSemestre(Semestre semestre) {
        jcbNumSemestre.setSelectedItem(semestre);
    }

    public Asignaturaenplanestudio getAsignaturaenplanestudio() {
        return asignaturaEnPlan;
    }
}
