/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.ComboBoxNumSemestre;
import business.ComboBoxPlanEstudios;
import business.HorarioSemestre;
import business.Observer;

/**
 *
 * @author Carlos
 */
public class VentHorarioSemestre extends javax.swing.JFrame {

    private String numProgAca;
    private int idProg;
    /**
     * Creates new form VentHorarioSemestre
     */
    public VentHorarioSemestre(String numProgAca, int idProg) {
        this.numProgAca = numProgAca;
        this.idProg = idProg;
        initComponents();
        setVisible(true);
        titulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlanEstudios = new javax.swing.JLabel();
        jComboBoxPlanEstudios = new ComboBoxPlanEstudios();
        lblSemestre = new javax.swing.JLabel();
        jComboBoxNumSemestre = new ComboBoxNumSemestre();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHorarioSemestre = new HorarioSemestre(idProg,(ComboBoxPlanEstudios)jComboBoxPlanEstudios);
        jToolBar1 = new BarraHerramientasTabla(jTableHorarioSemestre, this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblPlanEstudios.setText("Plan de estudio:");

        jComboBoxPlanEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlanEstudiosActionPerformed(evt);
            }
        });

        lblSemestre.setText("Semestre:");

        ((ComboBoxPlanEstudios)jComboBoxPlanEstudios).register((Observer)jComboBoxNumSemestre);
        jComboBoxNumSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumSemestreActionPerformed(evt);
            }
        });

        ((ComboBoxNumSemestre)jComboBoxNumSemestre).register((Observer)jTableHorarioSemestre);
        jScrollPane1.setViewportView(jTableHorarioSemestre);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblPlanEstudios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPlanEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblSemestre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxNumSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlanEstudios)
                    .addComponent(jComboBoxPlanEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemestre)
                    .addComponent(jComboBoxNumSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPlanEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlanEstudiosActionPerformed
        titulo();
    }//GEN-LAST:event_jComboBoxPlanEstudiosActionPerformed

    private void jComboBoxNumSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumSemestreActionPerformed
        titulo();
    }//GEN-LAST:event_jComboBoxNumSemestreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxNumSemestre;
    private javax.swing.JComboBox jComboBoxPlanEstudios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHorarioSemestre;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblPlanEstudios;
    private javax.swing.JLabel lblSemestre;
    // End of variables declaration//GEN-END:variables
    
    private void titulo(){
        String semestre = (jComboBoxNumSemestre.getSelectedItem()) == null ?  " (no seleccionado)" : (jComboBoxNumSemestre.getSelectedItem()).toString();
        String planEstudio = (jComboBoxPlanEstudios.getSelectedItem()) == null ? " (no seleccionado)" : (jComboBoxPlanEstudios.getSelectedItem()).toString();
        setTitle("Horario semestre " + semestre + " Plan estudio " + planEstudio + " - Programación Académica " + numProgAca);
    }

}
