/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdCrearProgDesdeAnterior;
import business.ButtonHandler;
import business.ComboBoxProgAcaAnt;
import dataDB.Progacademica;

/**
 *
 * @author Carlos
 */
public class VentCrearProgDesdeAnterior extends javax.swing.JFrame {

    /**
     * Creates new form VentCrearProgDesdeAnterior
     */
    public VentCrearProgDesdeAnterior() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProgAca = new javax.swing.JLabel();
        cbProgAcaAnterior = new ComboBoxProgAcaAnt();
        lblNombreNuevaProg = new javax.swing.JLabel();
        txtNombreNuevaProg = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nueva programación académica a partir de una anterior");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblProgAca.setText("Programación académica base:");

        lblNombreNuevaProg.setText("Nombre de la nueva programación académica:");

        btnAceptar.addActionListener(new ButtonHandler(new CmdCrearProgDesdeAnterior(this)));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnAceptar.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreNuevaProg)
                    .addComponent(lblProgAca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbProgAcaAnterior, 0, 174, Short.MAX_VALUE)
                        .addComponent(txtNombreNuevaProg)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgAca)
                    .addComponent(cbProgAcaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreNuevaProg)
                    .addComponent(txtNombreNuevaProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox cbProgAcaAnterior;
    private javax.swing.JLabel lblNombreNuevaProg;
    private javax.swing.JLabel lblProgAca;
    private javax.swing.JTextField txtNombreNuevaProg;
    // End of variables declaration//GEN-END:variables

    public String getNombreNuevaProgAca() {
        return txtNombreNuevaProg.getText().toUpperCase();
    }

    public Progacademica getProgAcaAnterior() {
        return (Progacademica) cbProgAcaAnterior.getSelectedItem();
    }

}
