/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdCrearSalon;
import business.ButtonHandler;
import business.ComboBoxEdificio;
import dataDB.Edificio;
import dataDB.Salon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VentCrearSalon extends JFrame {

    private Salon salon;

    /**
     * Creates new form VentCrearSalon
     */
    public VentCrearSalon() {
        initComponents();
        setVisible(true);
    }

    public VentCrearSalon(Salon salon) {
        this.salon = salon;
        initComponents();
        this.setNumEdificio(salon.getIdEdificio());
        this.setNumSalon(String.valueOf(salon.getNumeroSalon()));
        this.setObservaciones(salon.getObservaciones());
        this.setCapacidad(String.valueOf(salon.getCapacidad()));
        this.setActivo(salon.getActivo());
        this.jCkSalonActivo.setVisible(true);
        this.btnAdSalon.setText("Modificar");
        this.btnAdSalon.setActionCommand("Modificar");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumEdificio = new javax.swing.JLabel();
        lblNumSalon = new javax.swing.JLabel();
        lblCapacidad = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        txtNumSalon = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnAdSalon = new javax.swing.JButton();
        jCkSalonActivo = new javax.swing.JCheckBox();
        jCkSalonActivo.setSelected(true);
        jCkSalonActivo.setVisible(false);
        btnCancelar = new javax.swing.JButton();
        jCBNumEdificio = new ComboBoxEdificio();
        btnAgregarEdificio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nuevo salón");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblNumEdificio.setText("Número de edificio:");

        lblNumSalon.setText("Número de salón:");

        lblCapacidad.setText("Capacidad:");

        lblObservaciones.setText("Observaciones:");

        txtObservaciones.setColumns(15);
        txtObservaciones.setRows(3);
        jScrollPane1.setViewportView(txtObservaciones);

        btnAdSalon.addActionListener(new ButtonHandler(new business.CmdCrearSalon(this,btnAdSalon)));
        btnAdSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptarPeque.png"))); // NOI18N
        btnAdSalon.setText("Aceptar");

        jCkSalonActivo.setText("Activo");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregarEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/adicionarPeque.png"))); // NOI18N
        btnAgregarEdificio.setToolTipText("Agregar nuevo edificio");
        btnAgregarEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEdificioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblObservaciones)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdSalon))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumEdificio)
                            .addComponent(lblNumSalon)
                            .addComponent(lblCapacidad))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBNumEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCkSalonActivo))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarEdificio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumEdificio)
                        .addComponent(jCBNumEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSalon)
                    .addComponent(txtNumSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCkSalonActivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCapacidad))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblObservaciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdSalon)
                            .addComponent(btnCancelar))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cerrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEdificioActionPerformed
        new VentCrearEdificio((ComboBoxEdificio) jCBNumEdificio);
    }//GEN-LAST:event_btnAgregarEdificioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdSalon;
    private javax.swing.JButton btnAgregarEdificio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox jCBNumEdificio;
    private javax.swing.JCheckBox jCkSalonActivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblNumEdificio;
    private javax.swing.JLabel lblNumSalon;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtNumSalon;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables

    public Edificio getNumEdificio() {
        return (Edificio) jCBNumEdificio.getSelectedItem();
    }

    public String getNumSalon() {
        return txtNumSalon.getText().toUpperCase();
    }

    public String getCapacidad() {
        return txtCapacidad.getText();
    }

    public String getObservaciones() {
        return txtObservaciones.getText().toUpperCase();
    }

    public boolean getActivo() {
        return jCkSalonActivo.isSelected();
    }

    public void setActivo(boolean activo) {
        jCkSalonActivo.setSelected(activo);
    }

    public void setNumEdificio(Edificio edificio) {
        jCBNumEdificio.setSelectedItem(edificio);
    }

    public void setNumSalon(String numSalon) {
        txtNumSalon.setText(numSalon);
    }

    public void setCapacidad(String capacidad) {
        txtCapacidad.setText(capacidad);
    }

    public void setObservaciones(String observaciones) {
        txtObservaciones.setText(observaciones);
    }

    public Salon getSalon() {
        return this.salon;
    }

    public void confirmacionSalonAgregado() {
        JOptionPane.showMessageDialog(this, "Salón agregado exitosamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/GUI/iconos/salon.png")));
        this.setNumSalon("");
        this.setCapacidad("");
        this.setObservaciones("");
    }

    public void cerrar() {
        this.dispose();
    }

    public void confirmacionSalonModificado() {
        JOptionPane.showMessageDialog(this, "Salón modificado exitosamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/GUI/iconos/salon.png")));
    }
}
