/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.ButtonHandler;
import data.Usuario;
import javax.swing.JFrame;

/**
 *
 * @author Carlos
 */
public class VentCambiarPass extends JFrame {

    /**
     * Creates new form VentCambiarPass
     */
    private Usuario usuario;

    /**
     *
     * @param usuario representa al objeto usuario que está en la aplicación
     */
    public VentCambiarPass(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPassActual = new javax.swing.JLabel();
        lnlPassNueva = new javax.swing.JLabel();
        lblPassNuevaRe = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtPassNueva = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        btnCambiarPass = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambiar contraseña");
        setAlwaysOnTop(true);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        lblPassActual.setText("Contraseña actual:");

        lnlPassNueva.setText("Nueva contraseña:");

        lblPassNuevaRe.setText("Confirmar nueva contraseña:");

        btnCambiarPass.addActionListener(new ButtonHandler(new business.CmdCambiarPass(this, btnCambiarPass)));
        btnCambiarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/aceptar.png"))); // NOI18N
        btnCambiarPass.setText("Aceptar");

        lblCorreo.setText("Correo electrónico:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(btnCambiarPass)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassActual)
                    .addComponent(lblPassNuevaRe)
                    .addComponent(lnlPassNueva)
                    .addComponent(lblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassNueva, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(txtPassword)
                    .addComponent(txtRePassword)
                    .addComponent(txtCorreo))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassActual)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnlPassNueva)
                    .addComponent(txtPassNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassNuevaRe)
                    .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnCambiarPass)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarPass;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblPassActual;
    private javax.swing.JLabel lblPassNuevaRe;
    private javax.swing.JLabel lnlPassNueva;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPassNueva;
    protected javax.swing.JPasswordField txtPassword;
    protected javax.swing.JPasswordField txtRePassword;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return la contraseña actual digitada en el campo contraseña
     */
    public char[] getPassword() {
        return this.txtPassword.getPassword();
    }

    /**
     *
     * @return la nueva contraseña
     */
    public char[] getPassNueva() {
        return this.txtPassNueva.getPassword();
    }

    /**
     *
     * @return la repetición de la nueva contraseña
     */
    public char[] getRePassword() {
        return this.txtRePassword.getPassword();
    }

    /**
     *
     * @return el correo introducico en el campo correo electrónico
     */
    public String getCorreo() {
        return this.txtCorreo.getText();
    }

    /**
     *
     * @return el usuario que está en la aplicación
     */
    public Usuario getUsuario() {
        return usuario;
    }

}
