/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.CmdEliminarNivelEstudio;
import business.CmdModNivelEstudio;
import business.ButtonHandler;
import business.JChkVerOcultos;
import business.TablaNivelesEstudio;
import dataDB.Nivelestudio;

/**
 *
 * @author Carlos
 */
public class VentNivelesEstudio extends VentTabla {

    /**
     * Creates new form VentNivelesEstudio
     */
    public VentNivelesEstudio(boolean editable, boolean eliminable) {
        super(editable, eliminable);
        initComponents();
        inicializarBotones(editable, eliminable);
        setVisible(true);
    }

    public void cerrar() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new TablaNivelesEstudio();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jChkVerOcultos = new JChkVerOcultos(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Niveles de estudio");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/calendario.png")).getImage());
        setResizable(false);

        jScrollPane1.setViewportView(tabla);

        btnModificar.addActionListener(new ButtonHandler(new CmdModNivelEstudio(this)));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/editarPeque.png"))); // NOI18N
        btnModificar.setText("Modificar");

        btnEliminar.addActionListener(new ButtonHandler(new CmdEliminarNivelEstudio(this, btnEliminar)));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/iconos/eliminarPeque.png"))); // NOI18N
        btnEliminar.setText("Ocultar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jChkVerOcultos)
                        .addGap(33, 33, 33)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(jChkVerOcultos))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /*
    private javax.swing.JButton btnEliminar;
    */
    /*
    private javax.swing.JButton btnModificar;
    */
    /*
    private javax.swing.JCheckBox jChkVerOcultos;
    */
    private javax.swing.JScrollPane jScrollPane1;
    /*
    private javax.swing.JTable tabla;
    */
    // End of variables declaration//GEN-END:variables

    public Nivelestudio getNivelEstudio() {
        try {
            return (Nivelestudio) tabla.getModel().getValueAt(tabla.getSelectedRow(), 0);
        } catch (IndexOutOfBoundsException ex) {
            return null;
        }
    }

    public void removerFila() {
        ((TablaNivelesEstudio) tabla).removerFila();
    }
}
